export type ItemVisualData = {
  id?: string;
  name?: string;
  names?: Record<string, string | undefined>;
  description?: string;
  summaries?: Record<string, string | undefined>;
  traits?: string[];
  itemCategory?: string;
  category?: string;
  imageUrl?: string;
  image?: { url?: string; alt?: string };
};

function itemIdentity(data: ItemVisualData = {}): string {
  const names = data.names || {};
  return [data.name, names["pt-BR"], names.en, names.es, data.description, ...(data.traits || []), data.itemCategory, data.category]
    .filter(Boolean).join(" ").toLocaleLowerCase("pt-BR");
}

export function getItemVisualKey(data: ItemVisualData = {}): string {
  const identity = itemIdentity(data);
  const name = (data.name || "").trim().toLocaleLowerCase("pt-BR");
  if (data.id === "item.gear.adventurers_pack" || /^mochila de aventureiro$/.test(name)) return "adventurers-pack";
  if (data.id === "item.gear.healers_toolkit" || /^kit de primeiros socorros$/.test(name)) return "healers-first-aid-kit";
  if (data.id === "item.gear.thieves_toolkit" || /^ferramentas de ladr[aã]o$/.test(name)) return "thieves-tools";
  if (data.id === "item.magic.boots_of_elvenkind" || /^botas [eé]lficas$/.test(name)) return "elven-boots";
  if (data.id === "item.consumable.minor_healing_potion" || /^po[cç][aã]o de cura menor$/.test(name)) return "minor-healing-potion";
  if (data.id === "item.consumable.lesser_healing_potion" || /^po[cç][aã]o de cura inferior$/.test(name)) return "lesser-healing-potion";
  if (data.id === "item.gear.backpack" || /^mochila$/.test(name)) return "backpack";
  if (data.id === "item.pc2.spellguard_blade" || /^l[aâ]mina escuda-magia$/.test(name)) return "spellguard-blade";
  if (data.id === "item.pc2.dazzling_buckler" || /^broquel deslumbrante$/.test(name)) return "dazzling-buckler";
  if (data.id === "item.guns_gears.immaculate_holster" || /^coldre imaculado$/.test(name)) return "immaculate-holster";
  if (data.id === "item.guns_gears.amplifying_scope" || /^mira de amplifica[cç][aã]o$/.test(name)) return "amplifying-scope";
  if (data.id === "item.guns_gears.delineating_scope" || /^mira de delineamento$/.test(name)) return "delineating-scope";
  if (data.id === "item.guns_gears.scope_of_truth" || /^mira da verdade$/.test(name)) return "scope-of-truth";
  if (data.id === "item.guns_gears.darkvision_scope" || /^mira de vis[aã]o no escuro$/.test(name)) return "darkvision-scope";
  if (data.id === "item.rage_elements.water.faydhaans_dallah" || /^dallah de faydhaan$/.test(name)) return "faydhaans-dallah";
  if (data.id === "item.rage_elements.water.octopus_potion" || /^po[cç][aã]o de polvo$/.test(name)) return "octopus-potion";
  if (data.id === "item.rage_elements.air.blight_breath" || /^sopro da praga$/.test(name)) return "blight-breath";
  if (data.id === "item.rage_elements.earth.sairazul_blue" || /^azul de sairazul$/.test(name)) return "sairazul-blue";
  if (data.id === "item.guns_gears.snipers_saddle" || /^sela do atirador$/.test(name)) return "snipers-saddle";
  if (data.id === "item.guns_gears.immovable_tripod" || /^trip[eé] im[oó]vel$/.test(name)) return "immovable-tripod";
  if (data.id === "item.howl.hodag_leather" || /^couro de hodag$/.test(name)) return "hodag-leather";
  if (data.id === "item.howl.mamlambo_scale" || /^escama de mamlambo$/.test(name)) return "mamlambo-scale";
  if (data.id === "item.howl.mantis_plate" || /^placa de louva-a-deus$/.test(name)) return "mantis-plate";
  if (data.id === "item.howl.hippopotamus_klar" || /^klar de hipop[oó]tamo$/.test(name)) return "hippopotamus-klar";
  if (data.id === "item.howl.ankhrav_duster" || /^poeira de ankhrav$/.test(name)) return "ankhrav-duster";
  if (data.id === "item.howl.black_scorpion_stingmace" || /^ma[cç]a-ferr[aã]o de escorpi[aã]o negro$/.test(name)) return "black-scorpion-stingmace";
  if (data.id === "item.guns_gears.lucky_draw_bandolier" || /^bandoleira do saque da sorte$/.test(name)) return "lucky-draw-bandolier";
  if (data.id === "item.howl.shuln_fang_katar" || /^katar de presa shuln$/.test(name)) return "shuln-fang-katar";
  if (data.id === "item.howl.storm_herald" || /^arauto da tempestade$/.test(name)) return "storm-herald";
  if (data.id === "item.howl.trollhound_pick" || /^picareta de c[aã]o-troll$/.test(name)) return "trollhound-pick";
  if (data.id === "item.howl.alicorn_trigger" || /^gatilho de alic[oó]rnio$/.test(name)) return "alicorn-trigger";
  if (data.id === "item.howl.howler_pistol" || /^pistola uivante$/.test(name)) return "howler-pistol";
  if (data.id === "item.battlecry.repeater_bandolier" || /^bandoleira de repetidor$/.test(name)) return "repeater-bandolier";
  if (data.id === "item.battlecry.war_saddle" || /^sela de guerra$/.test(name)) return "war-saddle";
  if (data.id === "item.war_immortals.fishing_lure" || /^isca de pesca$/.test(name)) return "fishing-lure";
  if (data.id === "item.dark_archive.calamity_glass" || /^vidro da calamidade$/.test(name)) return "calamity-glass";
  if (data.id === "item.dark_archive.golden_goose" || /^ganso dourado$/.test(name)) return "golden-goose";
  if (data.id === "item.dark_archive.rose_of_loves_lost" || /^rosa dos amores perdidos$/.test(name)) return "rose-lost-loves";
  if (data.id === "item.dark_archive.cryolite_eye" || /^olho de criolita$/.test(name)) return "cryolite-eye";
  if (data.id === "item.dark_archive.hand_hewed_face" || /^rosto esculpido [aà] m[aã]o$/.test(name)) return "hand-hewed-face";
  if (data.id === "item.dark_archive.bottomless_purse" || /^bolsa inesgot[aá]vel$/.test(name)) return "bottomless-purse";
  if (data.id === "item.dark_archive.key_to_the_stomach" || /^chave do est[oô]mago$/.test(name)) return "key-to-stomach";
  if (data.id === "item.dark_archive.lost_ember" || /^brasa perdida$/.test(name)) return "lost-ember";
  if (data.id === "item.howl.fulmination_fang" || /^presa de fulmina[cç][aã]o$/.test(name)) return "fulmination-fang";
  if (data.id === "item.dark_archive.self_emptying_pocket" || /^bolso que se esvazia sozinho$/.test(name)) return "self-emptying-pocket";
  if (data.id === "item.dark_archive.stone_of_unrivaled_skill" || /^pedra da habilidade inigual[aá]vel$/.test(name)) return "stone-unrivaled-skill";
  if (data.id === "item.compendium.air_bladder" || /^bexiga de ar$/.test(name)) return "air-bladder";
  if (data.id === "item.compendium.alchemist_s_lab" || /^laborat[oó]rio de alquimista$/.test(name)) return "alchemists-lab";
  if (data.id === "item.compendium.alchemist_s_lab_expanded" || /^laborat[oó]rio de alquimista \(expandido\)$/.test(name)) return "alchemists-lab-expanded";
  if (data.id === "item.compendium.animal_blind" || /^abrigo de observa[cç][aã]o animal$/.test(name)) return "animal-blind";
  if (data.id === "item.compendium.animal_call" || /^chamado de animal$/.test(name)) return "animal-call";
  if (data.id === "item.compendium.artisan_s_toolkit" || /^kit de artes[aã]o$/.test(name)) return "artisans-toolkit";
  if (data.id === "item.compendium.artisan_s_toolkit_sterling" || /^kit de artes[aã]o esterlino$/.test(name)) return "sterling-artisans-toolkit";
  if (data.id === "item.compendium.atmospheric_breathing_suit" || /^traje de respira[cç][aã]o atmosf[eé]rica$/.test(name)) return "atmospheric-breathing-suit";
  if (data.id === "item.compendium.bandolier" || /^cartucheira$/.test(name)) return "bandolier";
  if (data.id === "item.compendium.bedroll" || /^saco de dormir$/.test(name)) return "bedroll";
  if (data.id === "item.compendium.caltrops" || /^estrepes$/.test(name)) return "caltrops";
  if (data.id === "item.compendium.candle" || /^vela$/.test(name)) return "candle";
  if (data.id === "item.compendium.chalk_10_pieces" || /^giz \(10 peda[cç]os\)$/.test(name)) return "chalk";
  if (data.id === "item.compendium.climbing_kit" || /^kit de escalada$/.test(name)) return "climbing-kit";
  if (data.id === "item.compendium.compass" || /^b[uú]ssola$/.test(name)) return "compass";
  if (data.id === "item.compendium.crowbar" || /^p[eé] de cabra$/.test(name)) return "crowbar";
  if (data.id === "item.compendium.lantern_bullseye" || /^lanterna de foco$/.test(name)) return "bullseye-lantern";
  if (data.id === "item.compendium.dueling_cape" || /^capa de duelo$/.test(name)) return "dueling-cape";
  if (data.id === "item.compendium.fishing_tackle" || /^equipamento de pesca$/.test(name)) return "fishing-tackle";
  if (data.id === "item.compendium.flint_and_steel" || /^pederneira e isqueiro$/.test(name)) return "flint-and-steel";
  if (data.id === "item.compendium.grappling_hook" || /^gancho de escalada$/.test(name)) return "grappling-hook";
  if (data.id === "item.compendium.lantern_hooded" || /^lanterna furta-fogo$/.test(name)) return "hooded-lantern";
  if (data.id === "item.compendium.lock_simple" || /^cadeado simples$/.test(name)) return "simple-padlock";
  if (data.id === "item.compendium.lock_average" || /^fechadura m[eé]dia$/.test(name)) return "average-lock";
  if (data.id === "item.compendium.magnifying_glass" || /^lupa$/.test(name)) return "magnifying-glass";
  if (data.id === "item.compendium.disguise_kit" || /^kit de disfarce$/.test(name)) return "disguise-kit";
  if (data.id === "item.compendium.manacles_simple" || /^algemas simples$/.test(name)) return "manacles-simple";
  if (data.id === "item.compendium.mirror" || /^espelho$/.test(name)) return "mirror";
  if (data.id === "item.compendium.spyglass" || /^luneta$/.test(name)) return "spyglass";
  if (data.id === "item.compendium.rations_1_week" || /^ra[cç][oõ]es \(1 semana\)$/.test(name)) return "rations-week";
  if (data.id === "item.compendium.rope_50_ft" || /^corda \(15 metros\)$/.test(name)) return "rope-15m";
  if (data.id === "item.compendium.sack" || /^saco$/.test(name)) return "sack";
  if (data.id === "item.compendium.signal_whistle" || /^apito de sinal$/.test(name)) return "signal-whistle";
  if (data.id === "item.compendium.torch" || /^tocha$/.test(name)) return "torch";
  if (data.id === "item.compendium.waterskin" || /^odre$/.test(name)) return "waterskin";
  if (data.id === "item.compendium.tindertwig" || /^graveto de igni[cç][aã]o$/.test(name)) return "tinder-twig";
  if (data.id === "item.compendium.soap" || /^sab[aã]o$/.test(name)) return "soap";
  if (data.id === "item.compendium.thieves_tools_infiltrator" || /^ferramentas de ladr[aã]o \(infiltrador\)$/.test(name)) return "infiltrator-thieves-tools";
  if (data.id === "item.compendium.spacious_pouch_bag_of_holding" || /^bolsa espa[cç]osa \(bolsa de carga\)$/.test(name)) return "spacious-pouch";
  if (data.id === "item.compendium.cloak_of_elvenkind" || /^manto [eé]lfico$/.test(name)) return "elven-cloak";
  if (data.id === "item.compendium.goggles_of_night" || /^[oó]culos da noite$/.test(name)) return "night-goggles";
  if (data.id === "item.rage_elements.wood.animal_nip" || /^mordida animal$/.test(name)) return "animal-nip";
  if (data.id === "item.rage_elements.wood.blooming_lotus_seed_pod" || /^vagem de sementes de l[oó]tus florescente$/.test(name)) return "lotus-seed-pod";
  if (data.id === "item.rage_elements.wood.captivating_rosebud" || /^bot[aã]o de rosa cativante$/.test(name)) return "captivating-rosebud";
  if (data.id === "item.rage_elements.wood.glowing_lantern_fruit" || /^fruto lanterna brilhante$/.test(name)) return "glowing-lantern-fruit";
  if (data.id === "item.rage_elements.water.aboutface_figurehead" || /^figura de proa meia-volta$/.test(name)) return "aboutface-figurehead";
  if (data.id === "item.rage_elements.water.anglerfish_lantern" || /^lanterna peixe-pescador$/.test(name)) return "anglerfish-lantern";
  if (data.id === "item.rage_elements.water.brine_dragon_scale" || /^escama de drag[aã]o de salmoura$/.test(name)) return "brine-dragon-scale";
  if (data.id === "item.rage_elements.water.conch_of_otherworldly_seas" || /^concha dos mares de outro mundo$/.test(name)) return "conch-otherworldly-seas";
  if (data.id === "item.rage_elements.water.kraken_figurehead" || /^figura de proa kraken$/.test(name)) return "kraken-figurehead";
  if (data.id === "item.rage_elements.water.sharkskin_robe" || /^robe de pele de tubar[aã]o$/.test(name)) return "sharkskin-robe";
  if (data.id === "item.rage_elements.water.shell_of_easy_breathing" || /^concha da respira[cç][aã]o f[aá]cil$/.test(name)) return "easy-breathing-shell";
  if (data.id === "item.rage_elements.water.veiled_figurehead" || /^figura de proa velada$/.test(name)) return "veiled-figurehead";
  if (data.id === "item.rage_elements.air.aerial_cloak" || /^manto a[eé]reo$/.test(name)) return "aerial-cloak";
  if (data.id === "item.rage_elements.air.extra_lung" || /^pulm[aã]o extra$/.test(name)) return "extra-lung";
  if (data.id === "item.rage_elements.air.fan_of_soothing_winds" || /^leque dos ventos calmantes$/.test(name)) return "soothing-winds-fan";
  if (data.id === "item.rage_elements.air.floating_tent" || /^tenda flutuante$/.test(name)) return "floating-tent";
  if (data.id === "item.rage_elements.air.frost_breath" || /^sopro g[eé]lido$/.test(name)) return "frost-breath";
  if (data.id === "item.rage_elements.air.jaathooms_scarf" || /^cachecol de jaathoom$/.test(name)) return "jaathoom-scarf";
  if (data.id === "item.rage_elements.air.nimbus_breath" || /^sopro de nimbo$/.test(name)) return "nimbus-breath";
  if (data.id === "item.rage_elements.air.spiral_chimes" || /^sinos espirais$/.test(name)) return "spiral-chimes";
  if (data.id === "item.rage_elements.earth.aeon_stone" || /^pedra aeon$/.test(name)) return "aeon-stone";
  if (data.id === "item.rage_elements.earth.drought_powder" || /^p[oó] da seca$/.test(name)) return "drought-powder";
  if (data.id === "item.rage_elements.earth.exuviae_powder" || /^p[oó] de ex[uú]via$/.test(name)) return "exuviae-powder";
  if (data.id === "item.rage_elements.earth.fossil_fragment" || /^fragmento f[oó]ssil$/.test(name)) return "fossil-fragment";
  if (data.id === "item.rage_elements.earth.jabalis_dice" || /^dados de jabali$/.test(name)) return "jabalis-dice";
  if (data.id === "item.rage_elements.earth.robe_of_stone" || /^robe de pedra$/.test(name)) return "stone-robe";
  if (data.id === "item.rage_elements.earth.sandcastle" || /^castelo de areia$/.test(name)) return "sandcastle";
  if (data.id === "item.rage_elements.earth.singing_stone" || /^pedra cantante$/.test(name)) return "singing-stone";
  if (data.id === "item.rage_elements.earth.stalagmite_seed" || /^semente de estalagmite$/.test(name)) return "stalagmite-seed";
  if (data.id === "item.rage_elements.earth.vital_earth" || /^terra vital$/.test(name)) return "vital-earth";
  if (data.id === "item.rage_elements.fire.ash_gown" || /^vestido de cinzas$/.test(name)) return "ash-gown";
  if (data.id === "item.rage_elements.fire.brazier_of_harmony" || /^braseiro da harmonia$/.test(name)) return "brazier-harmony";
  if (data.id === "item.rage_elements.fire.candle_of_inflamed_passions" || /^vela das paix[oõ]es inflamadas$/.test(name)) return "inflamed-passions-candle";
  if (data.id === "item.rage_elements.fire.everburning_coal" || /^carv[aã]o inextingu[ií]vel$/.test(name)) return "everburning-coal";
  if (data.id === "item.rage_elements.fire.globe_of_shrouds" || /^globo de mortalhas$/.test(name)) return "globe-shrouds";
  if (data.id === "item.rage_elements.fire.lambent_perfume" || /^perfume lampejante$/.test(name)) return "lambent-perfume";
  if (data.id === "item.rage_elements.fire.rhyton_of_the_radiant_ifrit" || /^r[ií]ton do ifrit radiante$/.test(name)) return "radiant-ifrit-rhyton";
  if (data.id === "item.rage_elements.fire.smoke_veil" || /^v[eé]u de fuma[cç]a$/.test(name)) return "smoke-veil";
  if (data.id === "item.rage_elements.fire.sparkshade_parasol" || /^sombrinha fagulhante$/.test(name)) return "sparkshade-parasol";
  if (data.id === "item.rage_elements.fire.thawing_candle" || /^vela do degelo$/.test(name)) return "thawing-candle";
  if (data.id === "item.howl.bloodgorger_scythe" || /^foice devorasangue$/.test(name)) return "bloodgorger-scythe";
  if (data.id === "item.howl.catoblepas_maul" || /^malho de catoblepas$/.test(name)) return "catoblepas-maul";
  if (data.id === "item.howl.chimera_flail" || /^mangual de quimera$/.test(name)) return "chimera-flail";
  if (data.id === "item.book_of_dead.vital_salt" || /^sal vital$/.test(name)) return "vital-salt";
  if (data.id === "item.dark_archive.vial_of_the_immortal_wellspring" || /^frasco da fonte imortal$/.test(name)) return "immortal-wellspring-vial";
  if (data.id === "item.compendium.elixir_of_life_minor" || /^elixir da vida \(menor\)$/.test(name)) return "minor-elixir-life";
  if (data.id === "item.compendium.elixir_of_life_lesser" || /^elixir da vida \(inferior\)$/.test(name)) return "lesser-elixir-life";
  if (data.id === "item.pc2.antiplague_lesser" || /^antipeste \(inferior\)$/.test(name)) return "lesser-antiplague";
  if (data.id === "item.pc2.minor_antidote" || /^ant[ií]doto menor$/.test(name)) return "minor-antidote";
  if (data.id === "item.compendium.alchemist_s_fire_lesser" || /^fogo alqu[ií]mico \(inferior\)$/.test(name)) return "lesser-alchemists-fire";
  if (data.id === "item.compendium.acid_flask_lesser" || /^frasco de [aá]cido \(inferior\)$/.test(name)) return "lesser-acid-flask";
  if (data.id === "item.compendium.frost_vial_lesser" || /^vial de frio \(inferior\)$/.test(name)) return "lesser-frost-vial";
  if (data.id === "item.compendium.bottled_lightning_lesser" || /^rel[aâ]mpago engarrafado \(inferior\)$/.test(name)) return "lesser-bottled-lightning";
  if (data.id === "item.guns_gears.ammunition.glue_bullet" || /^bala de cola$/.test(name)) return "glue-bullet";
  if (data.id === "item.guns_gears.ammunition.erosion_bullet" || /^bala da eros[aã]o$/.test(name)) return "erosion-bullet";
  if (data.id === "item.guns_gears.ammunition.faerie_bullet" || /^bala fe[eé]rica$/.test(name)) return "faerie-bullet";
  if (data.id === "item.guns_gears.ammunition.reliable_cartridge" || /^cartucho confi[aá]vel$/.test(name)) return "reliable-cartridge";
  if (data.id === "item.pc2.minor_glue_bomb" || /^bomba de cola menor$/.test(name)) return "minor-glue-bomb";
  if (data.id === "item.pc2.minor_weakening_bomb" || /^bomba de esmorecimento menor$/.test(name)) return "minor-weakening-bomb";
  if (data.id === "item.pc2.minor_ghost_charge" || /^carga fantasma menor$/.test(name)) return "minor-ghost-charge";
  if (data.id === "item.pc2.minor_detonating_stone" || /^pedra detonante menor$/.test(name)) return "minor-detonating-stone";
  if (data.id === "item.pc2.sailors_cota" || /^cota do marinheiro$/.test(name)) return "sailors-cota";
  if (data.id === "item.pc2.carnage_cuirass" || /^coura[cç]a da carnificina$/.test(name)) return "carnage-cuirass";
  if (data.id === "item.pc2.unholy_armor" || /^armadura profana$/.test(name)) return "unholy-armor";
  if (data.id === "item.pc2.dragon_scales" || /^placas de drag[aã]o$/.test(name)) return "dragon-scales";
  if (/^10 balas$|^10 bullets$/.test(name)) return "bullets";
  if (/^bandoleira do saque da sorte$|^manto a[eé]reo$|^figura de proa velada$/.test(name)) return "adventurer-pack";
  if (/^ervilhas estalantes terap[eê]uticas$|^sopro da praga$|^azul de sairazul$/.test(name)) return "potion";
  if (/^lan[cç]a peixe-le[aã]o$/.test(name)) return "spear";
  if (/^bomba de algas pegajosas$/.test(name)) return "bomb";
  if (/^tur[ií]bulo queima-sangue$/.test(name)) return "adventurer-pack";
  if (/^bast[aã]o de metal$|^bengala serpente de prata$/.test(name)) return "staff";
  if (/^runa de pot[eê]ncia de armadura/.test(name)) return "rune";
  if (/flecha|virote|muni[cç][aã]o|ammunition|cartucho|proj[eé]til|bala|disparo/.test(identity)) return "ammunition";
  if (/escudo|shield|baluarte/.test(identity)) return "shield";
  if (/armadura|armor|cota|coura[cç]a|placa peitoral|vestes|roupa de explorador/.test(identity)) return "armor";
  if (/cajado|bast[aã]o|staff|wand|varinha|vara m[aá]gica/.test(identity)) return "staff";
  if (/besta|crossbow|arbalesta/.test(identity)) return "crossbow";
  if (/arma de fogo|firearm|lan[cç]ador de espinhos|mosquete|bacamarte/.test(identity)) return "firearm";
  if (/chicote|whip/.test(identity)) return "whip";
  if (/arco|bow|cabe[cç]a-partida/.test(identity)) return "bow";
  if (/machado|axe|entalhador/.test(identity)) return "axe";
  if (/espada|sword|bengala-espada/.test(identity)) return "sword";
  if (/veneno|poison|toxina|ars[eê]nico|beladona|ac[oô]nito|cicuta|l[aá]grimas da morte|res[ií]duo de urtiga|resina de pragardente/.test(identity)) return "poison";
  if (/bomba|bomb|fogo alqu[ií]mico|carga fantasma|pedra detonante|ampola pavorosa|frasco congelante|frasco de [aá]cido|rel[aâ]mpago engarrafado/.test(identity)) return "bomb";
  if (/po[cç][aã]o|potion|elixir|soro|vial|frasco|ampola|t[oô]nico|lo[cç][aã]o|unguento|sal vital|[oó]leo/.test(identity)) return "potion";
  if (/runa|rune/.test(identity)) return "rune";
  if (/livro|book|t[aá]bua|grim[oó]rio|rascunho|tinta/.test(identity)) return "book";
  if (/anel|ring|pingente|colar|joia|jewel|c[aá]lice|broche|moeda|s[ií]mbolo religioso/.test(identity)) return "jewelry";
  return "adventurer-pack";
}

export function getItemImageUrl(data: ItemVisualData = {}): string {
  return data.image?.url || data.imageUrl || `/item-images/item-${getItemVisualKey(data)}.png`;
}

export function getItemImageAlt(name: string, data: ItemVisualData = {}, locale: "pt-BR" | "en" | "es" = "pt-BR"): string {
  if (data.image?.alt) return data.image.alt;
  const prefix = locale === "en" ? "Illustration of" : locale === "es" ? "Ilustración de" : "Ilustração de";
  return `${prefix} ${name}`;
}
