import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { getItemImageAlt, getItemImageUrl, getItemVisualKey } from "./itemVisuals";

describe("item visuals", () => {
  it.each([
    ["Bomba de Fogo Alquímico", "bomb"],
    ["Runa de Potência", "rune"],
    ["Virote", "ammunition"],
    ["Veneno de Beladona", "poison"],
    ["Livro de Rituais", "book"],
    ["Anel da Proteção", "jewelry"],
    ["Armadura de Placas Mágica", "armor"],
    ["Escudo do Guardião", "shield"],
    ["Cajado do Inverno", "staff"],
    ["Besta de Ver-Espírito", "crossbow"],
    ["Arco Cabeça-Partida", "bow"],
    ["Chicote de Lula Gigante", "whip"],
    ["Machado Entalhador", "axe"],
    ["Mochila de Aventureiro", "adventurers-pack"],
    ["Kit de Primeiros Socorros", "healers-first-aid-kit"],
    ["Ferramentas de Ladrão", "thieves-tools"],
    ["Botas Élficas", "elven-boots"],
    ["Poção de Cura Menor", "minor-healing-potion"],
    ["Poção de Cura Inferior", "lesser-healing-potion"],
    ["Mochila", "backpack"],
    ["Lâmina Escuda-Magia", "spellguard-blade"],
    ["Broquel Deslumbrante", "dazzling-buckler"],
    ["Coldre Imaculado", "immaculate-holster"],
    ["Mira de Amplificação", "amplifying-scope"],
    ["Mira de Delineamento", "delineating-scope"],
    ["Mira da Verdade", "scope-of-truth"],
    ["Mira de Visão no Escuro", "darkvision-scope"],
    ["Dallah de Faydhaan", "faydhaans-dallah"],
    ["Poção de Polvo", "octopus-potion"],
    ["Sopro da Praga", "blight-breath"],
    ["Azul de Sairazul", "sairazul-blue"],
    ["Sela do Atirador", "snipers-saddle"],
    ["Tripé Imóvel", "immovable-tripod"],
    ["Couro de Hodag", "hodag-leather"],
    ["Escama de Mamlambo", "mamlambo-scale"],
    ["Placa de Louva-a-Deus", "mantis-plate"],
    ["Klar de Hipopótamo", "hippopotamus-klar"],
    ["Poeira de Ankhrav", "ankhrav-duster"],
    ["Maça-Ferrão de Escorpião Negro", "black-scorpion-stingmace"],
    ["Bandoleira do Saque da Sorte", "lucky-draw-bandolier"],
    ["Foice Devorasangue", "bloodgorger-scythe"],
    ["Malho de Catoblepas", "catoblepas-maul"],
    ["Mangual de Quimera", "chimera-flail"],
    ["Katar de Presa Shuln", "shuln-fang-katar"],
    ["Arauto da Tempestade", "storm-herald"],
    ["Picareta de Cão-Troll", "trollhound-pick"],
    ["Gatilho de Alicórnio", "alicorn-trigger"],
    ["Pistola Uivante", "howler-pistol"],
    ["Bandoleira de Repetidor", "repeater-bandolier"],
    ["Sela de Guerra", "war-saddle"],
    ["Isca de Pesca", "fishing-lure"],
    ["Vidro da Calamidade", "calamity-glass"],
    ["Ganso Dourado", "golden-goose"],
    ["Rosa dos Amores Perdidos", "rose-lost-loves"],
    ["Olho de Criolita", "cryolite-eye"],
    ["Rosto Esculpido à Mão", "hand-hewed-face"],
    ["Bolsa Inesgotável", "bottomless-purse"],
    ["Chave do Estômago", "key-to-stomach"],
    ["Brasa Perdida", "lost-ember"],
    ["Presa de Fulminação", "fulmination-fang"],
    ["Bolso que se Esvazia Sozinho", "self-emptying-pocket"],
    ["Pedra da Habilidade Inigualável", "stone-unrivaled-skill"],
    ["Bexiga de Ar", "air-bladder"],
    ["Laboratório de Alquimista", "alchemists-lab"],
    ["Laboratório de Alquimista (Expandido)", "alchemists-lab-expanded"],
    ["Abrigo de Observação Animal", "animal-blind"],
    ["Chamado de Animal", "animal-call"],
    ["Kit de Artesão", "artisans-toolkit"],
    ["Kit de Artesão Esterlino", "sterling-artisans-toolkit"],
    ["Traje de Respiração Atmosférica", "atmospheric-breathing-suit"],
    ["Cartucheira", "bandolier"],
    ["Saco de Dormir", "bedroll"],
    ["Estrepes", "caltrops"],
    ["Vela", "candle"],
    ["Giz (10 pedaços)", "chalk"],
    ["Kit de Escalada", "climbing-kit"],
    ["Bússola", "compass"],
    ["Pé de Cabra", "crowbar"],
    ["Lanterna de Foco", "bullseye-lantern"],
    ["Capa de Duelo", "dueling-cape"],
    ["Equipamento de Pesca", "fishing-tackle"],
    ["Pederneira e Isqueiro", "flint-and-steel"],
    ["Gancho de Escalada", "grappling-hook"],
    ["Lanterna Furta-Fogo", "hooded-lantern"],
    ["Cadeado Simples", "simple-padlock"],
    ["Fechadura Média", "average-lock"],
    ["Lupa", "magnifying-glass"],
    ["Kit de Disfarce", "disguise-kit"],
    ["Algemas Simples", "manacles-simple"],
    ["Espelho", "mirror"],
    ["Luneta", "spyglass"],
    ["Rações (1 semana)", "rations-week"],
    ["Corda (15 metros)", "rope-15m"],
    ["Saco", "sack"],
    ["Apito de Sinal", "signal-whistle"],
    ["Tocha", "torch"],
    ["Odre", "waterskin"],
    ["Graveto de Ignição", "tinder-twig"],
    ["Sabão", "soap"],
    ["Ferramentas de Ladrão (Infiltrador)", "infiltrator-thieves-tools"],
    ["Bolsa Espaçosa (Bolsa de Carga)", "spacious-pouch"],
    ["Manto Élfico", "elven-cloak"],
    ["Óculos da Noite", "night-goggles"],
    ["Mordida Animal", "animal-nip"],
    ["Vagem de Sementes de Lótus Florescente", "lotus-seed-pod"],
    ["Botão de Rosa Cativante", "captivating-rosebud"],
    ["Fruto Lanterna Brilhante", "glowing-lantern-fruit"],
    ["Figura de Proa Meia-Volta", "aboutface-figurehead"],
    ["Lanterna Peixe-Pescador", "anglerfish-lantern"],
    ["Escama de Dragão de Salmoura", "brine-dragon-scale"],
    ["Concha dos Mares de Outro Mundo", "conch-otherworldly-seas"],
    ["Figura de Proa Kraken", "kraken-figurehead"],
    ["Robe de Pele de Tubarão", "sharkskin-robe"],
    ["Concha da Respiração Fácil", "easy-breathing-shell"],
    ["Figura de Proa Velada", "veiled-figurehead"],
    ["Manto Aéreo", "aerial-cloak"],
    ["Pulmão Extra", "extra-lung"],
    ["Leque dos Ventos Calmantes", "soothing-winds-fan"],
    ["Tenda Flutuante", "floating-tent"],
    ["Sopro Gélido", "frost-breath"],
    ["Cachecol de Jaathoom", "jaathoom-scarf"],
    ["Sopro de Nimbo", "nimbus-breath"],
    ["Sinos Espirais", "spiral-chimes"],
    ["Sal Vital", "vital-salt"],
    ["Frasco da Fonte Imortal", "immortal-wellspring-vial"],
    ["Elixir da Vida (Menor)", "minor-elixir-life"],
    ["Elixir da Vida (Inferior)", "lesser-elixir-life"],
    ["Antipeste (Inferior)", "lesser-antiplague"],
    ["Antídoto Menor", "minor-antidote"],
    ["Fogo Alquímico (Inferior)", "lesser-alchemists-fire"],
    ["Frasco de Ácido (Inferior)", "lesser-acid-flask"],
    ["Vial de Frio (Inferior)", "lesser-frost-vial"],
    ["Relâmpago Engarrafado (Inferior)", "lesser-bottled-lightning"],
    ["Bala de Cola", "glue-bullet"],
    ["Bala da Erosão", "erosion-bullet"],
    ["Bala Feérica", "faerie-bullet"],
    ["Cartucho Confiável", "reliable-cartridge"],
    ["Bomba de Cola Menor", "minor-glue-bomb"],
    ["Bomba de Esmorecimento Menor", "minor-weakening-bomb"],
    ["Carga Fantasma Menor", "minor-ghost-charge"],
    ["Pedra Detonante Menor", "minor-detonating-stone"],
    ["Cota do Marinheiro", "sailors-cota"],
    ["Couraça da Carnificina", "carnage-cuirass"],
    ["Armadura Profana", "unholy-armor"],
    ["Placas de Dragão", "dragon-scales"],
    ["10 Balas", "bullets"],
    ["Manto Aéreo", "aerial-cloak"],
    ["Lança Peixe-Leão", "spear"],
    ["Sopro da Praga", "blight-breath"],
    ["Bastão de Metal", "staff"],
    ["Runa de Potência de Armadura +1", "rune"],
  ])("classifies %s as %s", (name, key) => expect(getItemVisualKey({ name })).toBe(key));

  it("uses the complete localized display name in alt text", () => {
    expect(getItemImageAlt("Mochila de Aventureiro", { name: "Mochila de Aventureiro" })).toBe("Ilustração de Mochila de Aventureiro");
  });

  it("associa todos os itens catalogados a uma família e asset local existente", () => {
    const items = JSON.parse(readFileSync(resolve(process.cwd(), "scripts/catalog_data/catalog_items.json"), "utf8")) as Array<Record<string, unknown>>;
    for (const item of items) {
      const name = String(item.name_pt || item.name_en || "");
      const data = {
        id: String(item.id || ""),
        name,
        names: { "pt-BR": name, en: String(item.name_en || "") },
        description: String(item.description_pt || ""),
        category: String(item.category || ""),
        traits: Array.isArray(item.traits) ? item.traits as string[] : [],
      };
      const key = getItemVisualKey(data);
      const url = getItemImageUrl(data);
      expect(key, name).not.toBe("generic");
      expect(url, name).toMatch(new RegExp(`^/item-images/item-${key}\\.png$`));
      expect(existsSync(resolve(process.cwd(), "public", "item-images", `item-${key}.png`)), name).toBe(true);
    }
  });
});
