-- Primeiro lote de itens mágicos do Guia do Mestre (2014), pp. 150–154 e 209.
insert into public.catalog_items (id,name_pt,item_category,ruleset,source_book,source_page,data,system_id) values
('dnd5e.item_magico.adaga_envenenamento','Adaga de envenenamento','weapon','standard','D&D 5e — Guia do Mestre (2014)',150,'{"id":"dnd5e.item_magico.adaga_envenenamento","name":"Adaga de envenenamento","sourcePage":150,"category":"arma","summary":"Arma (adaga), rara","magical":true,"magicCategory":"medio","rarity":"raro","magicEffects":["+1 em ataques e dano.","Veneno uma vez por amanhecer: Constituição CD 15, 2d10 de veneno e envenenado por 1 minuto."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.algemas_dimensionais','Algemas dimensionais','treasure','standard','D&D 5e — Guia do Mestre (2014)',150,'{"id":"dnd5e.item_magico.algemas_dimensionais","name":"Algemas dimensionais","sourcePage":150,"category":"equipamento","summary":"Item maravilhoso, raro","magical":true,"magicCategory":"medio","rarity":"raro","magicEffects":["Impedem teletransporte e outros deslocamentos extradimensionais enquanto fechadas."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.aljava_ehlonna','Aljava de Ehlonna','treasure','standard','D&D 5e — Guia do Mestre (2014)',150,'{"id":"dnd5e.item_magico.aljava_ehlonna","name":"Aljava de Ehlonna","sourcePage":150,"category":"equipamento","summary":"Item maravilhoso, incomum","magical":true,"magicCategory":"menor","rarity":"incomum","magicEffects":["Compartimentos extradimensionais para flechas, azagaias e objetos longos; nunca pesa mais de 1 kg."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.amuletoprotecao_deteccao','Amuleto de proteção contra detecção e localização','treasure','standard','D&D 5e — Guia do Mestre (2014)',150,'{"id":"dnd5e.item_magico.amuletoprotecao_deteccao","name":"Amuleto de proteção contra detecção e localização","sourcePage":150,"category":"equipamento","summary":"Item maravilhoso, incomum","magical":true,"magicCategory":"menor","rarity":"incomum","magicEffects":["Esconde o portador de magias de adivinhação e sensores mágicos."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.amuletosaude','Amuleto de saúde','treasure','standard','D&D 5e — Guia do Mestre (2014)',150,'{"id":"dnd5e.item_magico.amuletosaude","name":"Amuleto de saúde","sourcePage":150,"category":"equipamento","summary":"Item maravilhoso, raro","magical":true,"magicCategory":"medio","rarity":"raro","magicEffects":["Constituição se torna 19 enquanto usado, se ainda não for maior."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.amuletoplanos','Amuleto dos planos','treasure','standard','D&D 5e — Guia do Mestre (2014)',150,'{"id":"dnd5e.item_magico.amuletoplanos","name":"Amuleto dos planos","sourcePage":150,"category":"equipamento","summary":"Item maravilhoso, muito raro","magical":true,"magicCategory":"maior","rarity":"muito_raro","magicEffects":["Pode tentar transportar o usuário para um local familiar em outro plano; Inteligência CD 15."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.anelandar_livre','Anel de andar livre','treasure','standard','D&D 5e — Guia do Mestre (2014)',151,'{"id":"dnd5e.item_magico.anelandar_livre","name":"Anel de andar livre","sourcePage":151,"category":"equipamento","summary":"Anel, raro","magical":true,"magicCategory":"medio","rarity":"raro","magicEffects":["Ignora terreno difícil e penalidades mágicas de movimento."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.anelariete','Anel aríete','treasure','standard','D&D 5e — Guia do Mestre (2014)',151,'{"id":"dnd5e.item_magico.anelariete","name":"Anel aríete","sourcePage":151,"category":"equipamento","summary":"Anel, raro","magical":true,"magicCategory":"medio","rarity":"raro","magicEffects":["Golpe de impacto à distância; possui cargas recuperadas diariamente."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.anelprotecao','Anel de proteção','treasure','standard','D&D 5e — Guia do Mestre (2014)',151,'{"id":"dnd5e.item_magico.anelprotecao","name":"Anel de proteção","sourcePage":151,"category":"equipamento","summary":"Anel, raro","magical":true,"magicCategory":"medio","rarity":"raro","magicEffects":["+1 na Classe de Armadura e nos testes de resistência."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.anelresistencia','Anel de resistência','treasure','standard','D&D 5e — Guia do Mestre (2014)',151,'{"id":"dnd5e.item_magico.anelresistencia","name":"Anel de resistência","sourcePage":151,"category":"equipamento","summary":"Anel, raro","magical":true,"magicCategory":"medio","rarity":"raro","magicEffects":["Resistência a um tipo de dano determinado pelo item."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.armadura_um','Armadura +1','armor','standard','D&D 5e — Guia do Mestre (2014)',152,'{"id":"dnd5e.item_magico.armadura_um","name":"Armadura +1","sourcePage":152,"category":"armadura","summary":"Armadura, incomum","magical":true,"magicCategory":"menor","rarity":"incomum","magicEffects":["+1 na Classe de Armadura além do bônus normal."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.arma_um','Arma +1','weapon','standard','D&D 5e — Guia do Mestre (2014)',152,'{"id":"dnd5e.item_magico.arma_um","name":"Arma +1","sourcePage":152,"category":"arma","summary":"Arma, incomum","magical":true,"magicCategory":"menor","rarity":"incomum","magicEffects":["+1 em jogadas de ataque e dano."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.bolsa_prestidigitacao','Bolsa de prestidigitação','treasure','standard','D&D 5e — Guia do Mestre (2014)',153,'{"id":"dnd5e.item_magico.bolsa_prestidigitacao","name":"Bolsa de prestidigitação","sourcePage":153,"category":"equipamento","summary":"Item maravilhoso, incomum","magical":true,"magicCategory":"menor","rarity":"incomum","magicEffects":["Produz pequenos objetos não mágicos; o conteúdo desaparece após ser retirado."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.botas_elficas','Botas élficas','treasure','standard','D&D 5e — Guia do Mestre (2014)',153,'{"id":"dnd5e.item_magico.botas_elficas","name":"Botas élficas","sourcePage":153,"category":"equipamento","summary":"Item maravilhoso, incomum","magical":true,"magicCategory":"menor","rarity":"incomum","magicEffects":["Passos silenciosos; vantagem em Furtividade baseada em movimento."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.botas_velocidade','Botas de velocidade','treasure','standard','D&D 5e — Guia do Mestre (2014)',153,'{"id":"dnd5e.item_magico.botas_velocidade","name":"Botas de velocidade","sourcePage":153,"category":"equipamento","summary":"Item maravilhoso, raro","magical":true,"magicCategory":"medio","rarity":"raro","magicEffects":["Aumentam o deslocamento e permitem movimento acelerado por até 10 minutos por carga."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.capa_elfica','Capa élfica','treasure','standard','D&D 5e — Guia do Mestre (2014)',154,'{"id":"dnd5e.item_magico.capa_elfica","name":"Capa élfica","sourcePage":154,"category":"equipamento","summary":"Item maravilhoso, incomum","magical":true,"magicCategory":"menor","rarity":"incomum","magicEffects":["Vantagem em Furtividade; Percepção para notar o usuário tem desvantagem."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.capa_deslocamento','Capa de deslocamento','treasure','standard','D&D 5e — Guia do Mestre (2014)',154,'{"id":"dnd5e.item_magico.capa_deslocamento","name":"Capa de deslocamento","sourcePage":154,"category":"equipamento","summary":"Item maravilhoso, raro","magical":true,"magicCategory":"medio","rarity":"raro","magicEffects":["Distorce a imagem do usuário, impondo desvantagem aos ataques contra ele até sofrer dano."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.pocao_cura','Poção de cura','consumable','standard','D&D 5e — Guia do Mestre (2014)',153,'{"id":"dnd5e.item_magico.pocao_cura","name":"Poção de cura","sourcePage":153,"category":"equipamento","summary":"Poção, comum","magical":true,"magicCategory":"uso_unico","rarity":"comum","magicEffects":["Consumir restaura 2d4 + 2 pontos de vida."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.pocao_escalada','Poção de escalada','consumable','standard','D&D 5e — Guia do Mestre (2014)',153,'{"id":"dnd5e.item_magico.pocao_escalada","name":"Poção de escalada","sourcePage":153,"category":"equipamento","summary":"Poção, comum","magical":true,"magicCategory":"uso_unico","rarity":"comum","magicEffects":["Deslocamento de escalada igual ao deslocamento por 1 hora e vantagem em Atletismo para escalar."]}'::jsonb,'dnd5e'),
('dnd5e.item_magico.varinha_misseis_magicos','Varinha de mísseis mágicos','treasure','standard','D&D 5e — Guia do Mestre (2014)',209,'{"id":"dnd5e.item_magico.varinha_misseis_magicos","name":"Varinha de mísseis mágicos","sourcePage":209,"category":"equipamento","summary":"Varinha, incomum","magical":true,"magicCategory":"menor","rarity":"incomum","magicEffects":["Possui 7 cargas e lança Mísseis mágicos; recupera 1d6 + 1 cargas diariamente."]}'::jsonb,'dnd5e')
on conflict (id) do update set name_pt=excluded.name_pt,item_category=excluded.item_category,ruleset=excluded.ruleset,source_book=excluded.source_book,source_page=excluded.source_page,data=excluded.data,system_id=excluded.system_id,updated_at=now();
