-- D&D 5e Livro do Jogador (2014): n�cleo de magias de 6� n�vel.
begin;
insert into public.catalog_spells (id,name_pt,rank,is_cantrip,is_focus,ruleset,source_book,source_page,data,system_id) values
('dnd5e.magia.ataque_visual','Ataque Visual',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.ataque_visual","name":"Ataque Visual","sourcePage":208,"category":"magia","summary":"6� n�vel � necromancia","spellLevel":6,"classIds":["bruxo","feiticeiro","mago"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.circulo_da_morte','C�rculo da Morte',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.circulo_da_morte","name":"C�rculo da Morte","sourcePage":208,"category":"magia","summary":"6� n�vel � necromancia","spellLevel":6,"classIds":["bruxo","feiticeiro","mago"],"castingTime":"1 a��o","range":"45 m","components":"V, S, M (uma p�rola negra de pelo menos 500 po)","duration":"Instant�nea","savingThrow":"Constitui��o"}'::jsonb,'dnd5e'),
('dnd5e.magia.conjurar_fada','Conjurar Fada',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.conjurar_fada","name":"Conjurar Fada","sourcePage":208,"category":"magia","summary":"6� n�vel � conjura��o","spellLevel":6,"classIds":["bruxo","druida"],"castingTime":"1 minuto","range":"27 m","components":"V, S","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.criar_mortos_vivos','Criar Mortos-Vivos',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.criar_mortos_vivos","name":"Criar Mortos-Vivos","sourcePage":208,"category":"magia","summary":"6� n�vel � necromancia","spellLevel":6,"classIds":["bruxo","clerigo","mago"],"castingTime":"1 minuto","range":"3 m","components":"V, S, M (um pote de argila cheio de terra de sepultura, um pote de argila cheio de �gua salgada e uma pedra de �nix de 150 po para cada cad�ver)","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.carne_para_pedra','Carne para Pedra',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.carne_para_pedra","name":"Carne para Pedra","sourcePage":208,"category":"magia","summary":"6� n�vel � transmuta��o","spellLevel":6,"classIds":["bruxo","mago"],"castingTime":"1 a��o","range":"18 m","components":"V, S, M (cal, �gua e terra)","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Constitui��o"}'::jsonb,'dnd5e'),
('dnd5e.magia.portal_arcano','Portal Arcano',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.portal_arcano","name":"Portal Arcano","sourcePage":208,"category":"magia","summary":"6� n�vel � conjura��o","spellLevel":6,"classIds":["bruxo","feiticeiro","mago"],"castingTime":"1 a��o","range":"150 m","components":"V, S","duration":"Concentra��o, at� 10 minutos","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.sugestao_em_massa','Sugest�o em Massa',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.sugestao_em_massa","name":"Sugest�o em Massa","sourcePage":208,"category":"magia","summary":"6� n�vel � encantamento","spellLevel":6,"classIds":["bruxo","feiticeiro","mago"],"castingTime":"1 a��o","range":"18 m","components":"V, M (uma l�ngua de cobra e um favo de mel)","duration":"24 horas","savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.visao_da_verdade','Vis�o da Verdade',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.visao_da_verdade","name":"Vis�o da Verdade","sourcePage":208,"category":"magia","summary":"6� n�vel � adivinha��o","spellLevel":6,"classIds":["bruxo","clerigo","druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"Toque","components":"V, S, M (uma pomada para os olhos que custa 25 po, feita de p� de cogumelo, a�afr�o e gordura)","duration":"1 hora"}'::jsonb,'dnd5e'),
('dnd5e.magia.aliado_planar','Aliado Planar',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.aliado_planar","name":"Aliado Planar","sourcePage":208,"category":"magia","summary":"6� n�vel � conjura��o","spellLevel":6,"classIds":["clerigo"],"castingTime":"10 minutos","range":"18 m","components":"V, S","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.barreira_de_laminas','Barreira de L�minas',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.barreira_de_laminas","name":"Barreira de L�minas","sourcePage":208,"category":"magia","summary":"6� n�vel � evoca��o","spellLevel":6,"classIds":["clerigo"],"castingTime":"1 a��o","range":"27 m","components":"V, S","duration":"Concentra��o, at� 10 minutos","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.cura_completa','Cura Completa',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.cura_completa","name":"Cura Completa","sourcePage":208,"category":"magia","summary":"6� n�vel � evoca��o","spellLevel":6,"classIds":["clerigo","druida"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.encontrar_o_caminho','Encontrar o Caminho',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.encontrar_o_caminho","name":"Encontrar o Caminho","sourcePage":208,"category":"magia","summary":"6� n�vel � adivinha��o","spellLevel":6,"classIds":["clerigo","druida"],"castingTime":"1 minuto","range":"Pessoal","components":"V, S, M (um conjunto de instrumentos de adivinha��o, como ossos, varetas, cartas, dentes ou runas, no valor de 100 po e um objeto do local que deseja encontrar)","duration":"Concentra��o, at� 1 dia","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.doenca_plena','Doen�a Plena',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.doenca_plena","name":"Doen�a Plena","sourcePage":208,"category":"magia","summary":"6� n�vel � necromancia","spellLevel":6,"classIds":["clerigo"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"7 dias","savingThrow":"Constitui��o"}'::jsonb,'dnd5e'),
('dnd5e.magia.banquete_dos_herois','Banquete dos Her�is',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.banquete_dos_herois","name":"Banquete dos Her�is","sourcePage":208,"category":"magia","summary":"6� n�vel � conjura��o","spellLevel":6,"classIds":["clerigo","druida"],"castingTime":"10 minutos","range":"9 m","components":"V, S, M (uma tigela incrustada de joias de pelo menos 1.000 po, consumida)","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.palavra_de_recordacao','Palavra de Recorda��o',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.palavra_de_recordacao","name":"Palavra de Recorda��o","sourcePage":208,"category":"magia","summary":"6� n�vel � conjura��o","spellLevel":6,"classIds":["clerigo"],"castingTime":"1 a��o","range":"5 km","components":"V","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.proibicao','Proibi��o',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.proibicao","name":"Proibi��o","sourcePage":208,"category":"magia","summary":"6� n�vel � abjura��o � ritual","spellLevel":6,"classIds":["clerigo"],"castingTime":"10 minutos","range":"Toque","components":"V, S, M (uma pitada de p� de rubi de 1.000 po, consumido)","duration":"1 dia","ritual":true}'::jsonb,'dnd5e'),
('dnd5e.magia.caminhar_no_vento','Caminhar no Vento',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.caminhar_no_vento","name":"Caminhar no Vento","sourcePage":209,"category":"magia","summary":"6� n�vel � transmuta��o","spellLevel":6,"classIds":["druida"],"castingTime":"1 minuto","range":"9 m","components":"V, S, M (fogo e �gua benta)","duration":"8 horas"}'::jsonb,'dnd5e'),
('dnd5e.magia.mover_terra','Mover Terra',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.mover_terra","name":"Mover Terra","sourcePage":209,"category":"magia","summary":"6� n�vel � transmuta��o","spellLevel":6,"classIds":["druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"36 m","components":"V, S, M (uma l�mina de ferro e uma pequena bolsa contendo uma mistura de solos: argila, barro e areia)","duration":"Concentra��o, at� 2 horas","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.muralha_de_espinhos','Muralha de Espinhos',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.muralha_de_espinhos","name":"Muralha de Espinhos","sourcePage":209,"category":"magia","summary":"6� n�vel � conjura��o","spellLevel":6,"classIds":["druida"],"castingTime":"1 a��o","range":"36 m","components":"V, S, M (um punhado de espinhos)","duration":"Concentra��o, at� 10 minutos","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.raio_solar','Raio Solar',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.raio_solar","name":"Raio Solar","sourcePage":209,"category":"magia","summary":"6� n�vel � evoca��o","spellLevel":6,"classIds":["druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"Pessoal (linha de 18 m)","components":"V, S, M (uma lente de aumento)","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Constitui��o"}'::jsonb,'dnd5e'),
('dnd5e.magia.teletransporte_por_arvores','Teletransporte por �rvores',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.teletransporte_por_arvores","name":"Teletransporte por �rvores","sourcePage":209,"category":"magia","summary":"6� n�vel � conjura��o","spellLevel":6,"classIds":["druida"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"1 rodada"}'::jsonb,'dnd5e'),
('dnd5e.magia.corrente_de_relampagos','Corrente de Rel�mpagos',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.corrente_de_relampagos","name":"Corrente de Rel�mpagos","sourcePage":210,"category":"magia","summary":"6� n�vel � evoca��o","spellLevel":6,"classIds":["feiticeiro","mago"],"castingTime":"1 a��o","range":"45 m","components":"V, S, M (um pouco de pelo; um peda�o de �mbar, vidro ou cristal; e tr�s alfinetes de prata)","duration":"Instant�nea","savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.desintegrar','Desintegrar',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.desintegrar","name":"Desintegrar","sourcePage":210,"category":"magia","summary":"6� n�vel � transmuta��o","spellLevel":6,"classIds":["feiticeiro","mago"],"castingTime":"1 a��o","range":"18 m","components":"V, S, M (uma magnetita e uma pitada de poeira)","duration":"Instant�nea","savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.globo_de_invulnerabilidade','Globo de Invulnerabilidade',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.globo_de_invulnerabilidade","name":"Globo de Invulnerabilidade","sourcePage":210,"category":"magia","summary":"6� n�vel � abjura��o","spellLevel":6,"classIds":["feiticeiro","mago"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S, M (uma conta de vidro ou cristal)","duration":"Concentra��o, at� 1 minuto","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.danca_irresistivel_otto','Dan�a Irresist�vel de Otto',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.danca_irresistivel_otto","name":"Dan�a Irresist�vel de Otto","sourcePage":211,"category":"magia","summary":"6� n�vel � encantamento","spellLevel":6,"classIds":["mago"],"castingTime":"1 a��o","range":"9 m","components":"V","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.contingencia','Conting�ncia',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.contingencia","name":"Conting�ncia","sourcePage":211,"category":"magia","summary":"6� n�vel � evoca��o","spellLevel":6,"classIds":["mago"],"castingTime":"10 minutos","range":"Pessoal","components":"V, S, M (uma estatueta de voc� esculpida em marfim e decorada com gemas valendo pelo menos 1.500 po)","duration":"10 dias"}'::jsonb,'dnd5e'),
('dnd5e.magia.muralha_de_gelo','Muralha de Gelo',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.muralha_de_gelo","name":"Muralha de Gelo","sourcePage":211,"category":"magia","summary":"6� n�vel � evoca��o","spellLevel":6,"classIds":["mago"],"castingTime":"1 a��o","range":"36 m","components":"V, S, M (um pequeno peda�o de quartzo)","duration":"Concentra��o, at� 10 minutos","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.recipiente_arcano','Recipiente Arcano',6,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.recipiente_arcano","name":"Recipiente Arcano","sourcePage":211,"category":"magia","summary":"6� n�vel � necromancia","spellLevel":6,"classIds":["mago"],"castingTime":"1 minuto","range":"Pessoal","components":"V, S, M (uma gema, cristal ou rel�quia valendo pelo menos 500 po)","duration":"At� ser dissipada"}'::jsonb,'dnd5e')
on conflict (id) do update set name_pt=excluded.name_pt,rank=excluded.rank,is_cantrip=excluded.is_cantrip,is_focus=excluded.is_focus,ruleset=excluded.ruleset,source_book=excluded.source_book,source_page=excluded.source_page,data=excluded.data,system_id=excluded.system_id,updated_at=now();
commit;
