-- D&D 5e Livro do Jogador (2014): n�cleo de magias de 8� n�vel.
begin;
insert into public.catalog_spells (id,name_pt,rank,is_cantrip,is_focus,ruleset,source_book,source_page,data,system_id) values
('dnd5e.magia.dominar_monstro','Dominar Monstro',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.dominar_monstro","name":"Dominar Monstro","sourcePage":208,"category":"magia","summary":"8� n�vel � encantamento","spellLevel":8,"classIds":["bruxo","feiticeiro","mago"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"Concentra��o, at� 1 hora","concentration":true,"savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.enfraquecer_intelecto','Enfraquecer o Intelecto',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.enfraquecer_intelecto","name":"Enfraquecer o Intelecto","sourcePage":208,"category":"magia","summary":"8� n�vel � encantamento","spellLevel":8,"classIds":["bruxo","druida","mago"],"castingTime":"1 a��o","range":"45 m","components":"V, S, M (um punhado de argila, cristal, vidro ou esferas minerais)","duration":"Instant�nea","savingThrow":"Intelig�ncia"}'::jsonb,'dnd5e'),
('dnd5e.magia.loquacidade','Loquacidade',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.loquacidade","name":"Loquacidade","sourcePage":208,"category":"magia","summary":"8� n�vel � transmuta��o","spellLevel":8,"classIds":["bruxo"],"castingTime":"1 a��o","range":"Pessoal","components":"V","duration":"1 hora"}'::jsonb,'dnd5e'),
('dnd5e.magia.palavra_de_poder_atordoar','Palavra de Poder Atordoar',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.palavra_de_poder_atordoar","name":"Palavra de Poder Atordoar","sourcePage":208,"category":"magia","summary":"8� n�vel � encantamento","spellLevel":8,"classIds":["bruxo","feiticeiro","mago"],"castingTime":"1 a��o","range":"18 m","components":"V","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.semiplano','Semiplano',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.semiplano","name":"Semiplano","sourcePage":208,"category":"magia","summary":"8� n�vel � conjura��o","spellLevel":8,"classIds":["bruxo","mago"],"castingTime":"1 a��o","range":"18 m","components":"S","duration":"1 hora"}'::jsonb,'dnd5e'),
('dnd5e.magia.aura_sagrada','Aura Sagrada',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.aura_sagrada","name":"Aura Sagrada","sourcePage":208,"category":"magia","summary":"8� n�vel � abjura��o","spellLevel":8,"classIds":["clerigo"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S, M (um pequeno relic�rio no valor de pelo menos 1.000 po, contendo uma rel�quia sagrada)","duration":"Concentra��o, at� 1 minuto","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.campo_antimagia','Campo Antimagia',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.campo_antimagia","name":"Campo Antimagia","sourcePage":208,"category":"magia","summary":"8� n�vel � abjura��o","spellLevel":8,"classIds":["clerigo","mago"],"castingTime":"1 a��o","range":"Pessoal (esfera de 3 m de raio)","components":"V, S, M (uma pitada de p� de ferro ou limalha de ferro)","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.controlar_o_clima','Controlar o Clima',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.controlar_o_clima","name":"Controlar o Clima","sourcePage":208,"category":"magia","summary":"8� n�vel � transmuta��o","spellLevel":8,"classIds":["clerigo","druida","mago"],"castingTime":"10 minutos","range":"Pessoal (raio de 7,5 km)","components":"V, S, M (incenso e peda�os de terra e madeira misturados em �gua)","duration":"Concentra��o, at� 8 horas","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.terremoto','Terremoto',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.terremoto","name":"Terremoto","sourcePage":208,"category":"magia","summary":"8� n�vel � evoca��o","spellLevel":8,"classIds":["clerigo","druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"150 m","components":"V, S, M (uma pitada de terra, um peda�o de rocha e um peda�o de argila)","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.antipatia_simpatia','Antipatia/Simpatia',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.antipatia_simpatia","name":"Antipatia/Simpatia","sourcePage":209,"category":"magia","summary":"8� n�vel � encantamento","spellLevel":8,"classIds":["druida","mago"],"castingTime":"1 hora","range":"18 m","components":"V, S, M (um peda�o de al�men embebido em vinagre)","duration":"10 dias","savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.explosao_solar','Explos�o Solar',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.explosao_solar","name":"Explos�o Solar","sourcePage":209,"category":"magia","summary":"8� n�vel � evoca��o","spellLevel":8,"classIds":["druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"45 m","components":"V, S, M (fogo e um peda�o de pedra do sol)","duration":"Instant�nea","savingThrow":"Constitui��o"}'::jsonb,'dnd5e'),
('dnd5e.magia.formas_animais','Formas Animais',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.formas_animais","name":"Formas Animais","sourcePage":209,"category":"magia","summary":"8� n�vel � transmuta��o","spellLevel":8,"classIds":["druida"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"Concentra��o, at� 24 horas","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.tsunami','Tsunami',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.tsunami","name":"Tsunami","sourcePage":209,"category":"magia","summary":"8� n�vel � conjura��o","spellLevel":8,"classIds":["druida"],"castingTime":"1 minuto","range":"1,5 km","components":"V, S","duration":"Concentra��o, at� 6 rodadas","concentration":true,"savingThrow":"For�a"}'::jsonb,'dnd5e'),
('dnd5e.magia.nuvem_incendiaria','Nuvem Incendi�ria',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.nuvem_incendiaria","name":"Nuvem Incendi�ria","sourcePage":210,"category":"magia","summary":"8� n�vel � conjura��o","spellLevel":8,"classIds":["feiticeiro","mago"],"castingTime":"1 a��o","range":"45 m","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.clone','Clone',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.clone","name":"Clone","sourcePage":211,"category":"magia","summary":"8� n�vel � necromancia","spellLevel":8,"classIds":["mago"],"castingTime":"1 hora","range":"Toque","components":"V, S, M (um diamante de pelo menos 1.000 po e pelo menos 1 polegada c�bica de carne da criatura duplicada, consumido)","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.labirinto','Labirinto',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.labirinto","name":"Labirinto","sourcePage":211,"category":"magia","summary":"8� n�vel � conjura��o","spellLevel":8,"classIds":["mago"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"Concentra��o, at� 10 minutos","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.limpar_a_mente','Limpar a Mente',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.limpar_a_mente","name":"Limpar a Mente","sourcePage":211,"category":"magia","summary":"8� n�vel � abjura��o","spellLevel":8,"classIds":["mago"],"castingTime":"1 a��o","range":"Toque","components":"V, S","duration":"24 horas"}'::jsonb,'dnd5e'),
('dnd5e.magia.telepatia','Telepatia',8,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.telepatia","name":"Telepatia","sourcePage":211,"category":"magia","summary":"8� n�vel � evoca��o","spellLevel":8,"classIds":["mago"],"castingTime":"1 a��o","range":"Ilimitado","components":"V, S, M (um par de an�is de prata unidos)","duration":"24 horas"}'::jsonb,'dnd5e')
on conflict (id) do update set name_pt=excluded.name_pt,rank=excluded.rank,is_cantrip=excluded.is_cantrip,is_focus=excluded.is_focus,ruleset=excluded.ruleset,source_book=excluded.source_book,source_page=excluded.source_page,data=excluded.data,system_id=excluded.system_id,updated_at=now();
commit;
