-- D&D 5e Livro do Jogador (2014): n�cleo adicional de magias de 3� n�vel.
begin;
insert into public.catalog_spells (id,name_pt,rank,is_cantrip,is_focus,ruleset,source_book,source_page,data,system_id) values
('dnd5e.magia.animar_mortos','Animar Mortos',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.animar_mortos","name":"Animar Mortos","sourcePage":211,"category":"magia","summary":"3� n�vel � necromancia","spellLevel":3,"classIds":["clerigo","mago"],"castingTime":"1 minuto","range":"3 m","components":"V, S, M (uma gota de sangue, um peda�o de carne e uma pitada de p� de osso)","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.circulo_magico','C�rculo M�gico',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.circulo_magico","name":"C�rculo M�gico","sourcePage":208,"category":"magia","summary":"3� n�vel � abjura��o","spellLevel":3,"classIds":["clerigo","bruxo","mago","paladino"],"castingTime":"1 minuto","range":"3 m","components":"V, S, M (�gua benta ou p� de prata e ferro, consumidos)","duration":"1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.clarividencia','Clarivid�ncia',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.clarividencia","name":"Clarivid�ncia","sourcePage":208,"category":"magia","summary":"3� n�vel � adivinha��o","spellLevel":3,"classIds":["clerigo","feiticeiro","mago"],"castingTime":"10 minutos","range":"1,5 km","components":"V, S, M (um foco de pelo menos 100 po)","duration":"Concentra��o, at� 10 minutos","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.enviar_mensagem','Enviar Mensagem',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.enviar_mensagem","name":"Enviar Mensagem","sourcePage":208,"category":"magia","summary":"3� n�vel � evoca��o","spellLevel":3,"classIds":["clerigo","mago"],"castingTime":"1 a��o","range":"Ilimitado","components":"V, S, M (um pequeno peda�o de fio de cobre)","duration":"1 rodada"}'::jsonb,'dnd5e'),
('dnd5e.magia.espiritos_guardioes','Esp�ritos Guardi�es',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.espiritos_guardioes","name":"Esp�ritos Guardi�es","sourcePage":208,"category":"magia","summary":"3� n�vel � conjura��o","spellLevel":3,"classIds":["clerigo"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S, M (um s�mbolo sagrado)","duration":"Concentra��o, at� 10 minutos","concentration":true,"savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.forjar_morte','Forjar Morte',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.forjar_morte","name":"Forjar Morte","sourcePage":208,"category":"magia","summary":"3� n�vel � necromancia � ritual","spellLevel":3,"classIds":["clerigo","druida","mago"],"castingTime":"1 a��o","range":"Toque","components":"V, S, M (uma pitada de terra de cemit�rio)","duration":"1 hora","ritual":true}'::jsonb,'dnd5e'),
('dnd5e.magia.glifo_de_vigilancia','Glifo de Vigil�ncia',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.glifo_de_vigilancia","name":"Glifo de Vigil�ncia","sourcePage":208,"category":"magia","summary":"3� n�vel � abjura��o","spellLevel":3,"classIds":["clerigo","mago"],"castingTime":"1 hora","range":"Toque","components":"V, S, M (incenso e p� de diamante de pelo menos 200 po, consumidos)","duration":"At� ser dissipado"}'::jsonb,'dnd5e'),
('dnd5e.magia.idiomas','Idiomas',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.idiomas","name":"Idiomas","sourcePage":208,"category":"magia","summary":"3� n�vel � adivinha��o","spellLevel":3,"classIds":["clerigo","bruxo","feiticeiro","mago"],"castingTime":"1 a��o","range":"Toque","components":"V, M (uma pequena est�tua de barro de um zigurate)","duration":"1 hora"}'::jsonb,'dnd5e'),
('dnd5e.magia.luz_do_dia','Luz do Dia',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.luz_do_dia","name":"Luz do Dia","sourcePage":208,"category":"magia","summary":"3� n�vel � evoca��o","spellLevel":3,"classIds":["clerigo","druida","feiticeiro","mago","paladino","patrulheiro"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"1 hora"}'::jsonb,'dnd5e'),
('dnd5e.magia.protecao_contra_energia','Prote��o contra Energia',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.protecao_contra_energia","name":"Prote��o contra Energia","sourcePage":208,"category":"magia","summary":"3� n�vel � abjura��o","spellLevel":3,"classIds":["clerigo","druida","feiticeiro","mago","patrulheiro"],"castingTime":"1 a��o","range":"Toque","components":"V, S","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.revivificar','Revivificar',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.revivificar","name":"Revivificar","sourcePage":208,"category":"magia","summary":"3� n�vel � necromancia","spellLevel":3,"classIds":["clerigo","paladino"],"castingTime":"1 a��o","range":"Toque","components":"V, S, M (um diamante de pelo menos 300 po, consumido)","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.rogar_maldicao','Rogar Maldi��o',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.rogar_maldicao","name":"Rogar Maldi��o","sourcePage":208,"category":"magia","summary":"3� n�vel � necromancia","spellLevel":3,"classIds":["clerigo","mago"],"castingTime":"1 a��o","range":"Toque","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.toque_vampirico','Toque Vamp�rico',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.toque_vampirico","name":"Toque Vamp�rico","sourcePage":208,"category":"magia","summary":"3� n�vel � necromancia","spellLevel":3,"classIds":["bruxo","mago"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.andar_na_agua','Andar na �gua',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.andar_na_agua","name":"Andar na �gua","sourcePage":209,"category":"magia","summary":"3� n�vel � transmuta��o � ritual","spellLevel":3,"classIds":["clerigo","druida","feiticeiro","patrulheiro"],"castingTime":"1 a��o","range":"9 m","components":"V, S, M (um peda�o de corti�a)","duration":"1 hora","ritual":true}'::jsonb,'dnd5e'),
('dnd5e.magia.ampliar_plantas','Ampliar Plantas',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.ampliar_plantas","name":"Ampliar Plantas","sourcePage":209,"category":"magia","summary":"3� n�vel � transmuta��o","spellLevel":3,"classIds":["druida","patrulheiro"],"castingTime":"1 a��o","range":"45 m","components":"V, S","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.conjurar_animais','Conjurar Animais',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.conjurar_animais","name":"Conjurar Animais","sourcePage":209,"category":"magia","summary":"3� n�vel � conjura��o","spellLevel":3,"classIds":["druida","patrulheiro"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.convocar_relampagos','Convocar Rel�mpagos',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.convocar_relampagos","name":"Convocar Rel�mpagos","sourcePage":209,"category":"magia","summary":"3� n�vel � conjura��o","spellLevel":3,"classIds":["druida"],"castingTime":"1 a��o","range":"36 m","components":"V, S","duration":"Concentra��o, at� 10 minutos","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.falar_com_plantas','Falar com Plantas',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.falar_com_plantas","name":"Falar com Plantas","sourcePage":209,"category":"magia","summary":"3� n�vel � transmuta��o","spellLevel":3,"classIds":["druida","patrulheiro"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"10 minutos"}'::jsonb,'dnd5e'),
('dnd5e.magia.muralha_de_vento','Muralha de Vento',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.muralha_de_vento","name":"Muralha de Vento","sourcePage":209,"category":"magia","summary":"3� n�vel � evoca��o","spellLevel":3,"classIds":["druida","patrulheiro"],"castingTime":"1 a��o","range":"36 m","components":"V, S, M (um pequeno leque e uma pena de origem ex�tica)","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"For�a"}'::jsonb,'dnd5e'),
('dnd5e.magia.nevasca','Nevasca',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.nevasca","name":"Nevasca","sourcePage":209,"category":"magia","summary":"3� n�vel � conjura��o","spellLevel":3,"classIds":["druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"45 m","components":"V, S, M (uma pitada de poeira e algumas gotas de �gua)","duration":"Concentra��o, at� 1 minuto","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.respirar_na_agua','Respirar na �gua',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.respirar_na_agua","name":"Respirar na �gua","sourcePage":209,"category":"magia","summary":"3� n�vel � transmuta��o � ritual","spellLevel":3,"classIds":["druida","feiticeiro","mago","patrulheiro"],"castingTime":"1 a��o","range":"9 m","components":"V, S, M (um peda�o de cana ou palha)","duration":"24 horas","ritual":true}'::jsonb,'dnd5e'),
('dnd5e.magia.arma_elemental','Arma Elemental',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',212,'{"id":"dnd5e.magia.arma_elemental","name":"Arma Elemental","sourcePage":212,"category":"magia","summary":"3� n�vel � transmuta��o","spellLevel":3,"classIds":["paladino"],"castingTime":"1 a��o","range":"Toque","components":"V, S","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.aura_de_vitalidade','Aura de Vitalidade',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',212,'{"id":"dnd5e.magia.aura_de_vitalidade","name":"Aura de Vitalidade","sourcePage":212,"category":"magia","summary":"3� n�vel � evoca��o","spellLevel":3,"classIds":["paladino"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.criar_alimentos','Criar Alimentos',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',212,'{"id":"dnd5e.magia.criar_alimentos","name":"Criar Alimentos","sourcePage":212,"category":"magia","summary":"3� n�vel � conjura��o","spellLevel":3,"classIds":["clerigo","paladino"],"castingTime":"1 a��o","range":"9 m","components":"V, S","duration":"24 horas"}'::jsonb,'dnd5e'),
('dnd5e.magia.manto_do_cruzado','Manto do Cruzado',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',212,'{"id":"dnd5e.magia.manto_do_cruzado","name":"Manto do Cruzado","sourcePage":212,"category":"magia","summary":"3� n�vel � evoca��o","spellLevel":3,"classIds":["paladino"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.conjurar_rajada','Conjurar Rajada',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',212,'{"id":"dnd5e.magia.conjurar_rajada","name":"Conjurar Rajada","sourcePage":212,"category":"magia","summary":"3� n�vel � conjura��o","spellLevel":3,"classIds":["patrulheiro"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S, M (uma muni��o ou arma)","duration":"Instant�nea","savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.flecha_relampageante','Flecha Relampejante',3,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',212,'{"id":"dnd5e.magia.flecha_relampageante","name":"Flecha Relampejante","sourcePage":212,"category":"magia","summary":"3� n�vel � transmuta��o","spellLevel":3,"classIds":["patrulheiro"],"castingTime":"1 a��o b�nus","range":"Pessoal","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e')
on conflict (id) do update set name_pt=excluded.name_pt,rank=excluded.rank,is_cantrip=excluded.is_cantrip,is_focus=excluded.is_focus,ruleset=excluded.ruleset,source_book=excluded.source_book,source_page=excluded.source_page,data=excluded.data,system_id=excluded.system_id,updated_at=now();
commit;
