-- D&D 5e Livro do Jogador (2014): n�cleo de magias de 9� n�vel.
begin;
insert into public.catalog_spells (id,name_pt,rank,is_cantrip,is_focus,ruleset,source_book,source_page,data,system_id) values
('dnd5e.magia.aprisionamento','Aprisionamento',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.aprisionamento","name":"Aprisionamento","sourcePage":208,"category":"magia","summary":"9� n�vel � abjura��o","spellLevel":9,"classIds":["bruxo","mago"],"castingTime":"1 minuto","range":"18 m","components":"V, S, M (uma representa��o em velino ou uma estatueta esculpida � semelhan�a do alvo e um componente especial, vari�vel conforme a vers�o escolhida)","duration":"At� ser dissipada","savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.metamorfose_verdadeira','Metamorfose Verdadeira',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.metamorfose_verdadeira","name":"Metamorfose Verdadeira","sourcePage":208,"category":"magia","summary":"9� n�vel � transmuta��o","spellLevel":9,"classIds":["bruxo","mago"],"castingTime":"1 a��o","range":"9 m","components":"V, S, M (uma gota de merc�rio, uma colher de goma ar�bica e uma fuma�a)","duration":"Concentra��o, at� 1 hora","concentration":true,"savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.palavra_de_poder_matar','Palavra de Poder Matar',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.palavra_de_poder_matar","name":"Palavra de Poder Matar","sourcePage":208,"category":"magia","summary":"9� n�vel � encantamento","spellLevel":9,"classIds":["bruxo","feiticeiro","mago"],"castingTime":"1 a��o","range":"18 m","components":"V","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.projecao_astral','Proje��o Astral',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.projecao_astral","name":"Proje��o Astral","sourcePage":208,"category":"magia","summary":"9� n�vel � necromancia","spellLevel":9,"classIds":["bruxo","clerigo","mago"],"castingTime":"1 hora","range":"3 m","components":"V, S, M (para cada criatura afetada, uma jacintha de pelo menos 1.000 po e uma barra de prata ornamentada de pelo menos 100 po, consumidas)","duration":"Especial"}'::jsonb,'dnd5e'),
('dnd5e.magia.sexto_sentido','Sexto Sentido',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.sexto_sentido","name":"Sexto Sentido","sourcePage":208,"category":"magia","summary":"9� n�vel � adivinha��o","spellLevel":9,"classIds":["bruxo","druida","mago"],"castingTime":"1 minuto","range":"Toque","components":"V, S, M (uma pena de colibri)","duration":"8 horas"}'::jsonb,'dnd5e'),
('dnd5e.magia.cura_completa_massa','Cura Completa em Massa',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.cura_completa_massa","name":"Cura Completa em Massa","sourcePage":208,"category":"magia","summary":"9� n�vel � evoca��o","spellLevel":9,"classIds":["clerigo"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.portal','Portal',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.portal","name":"Portal","sourcePage":208,"category":"magia","summary":"9� n�vel � conjura��o","spellLevel":9,"classIds":["clerigo","feiticeiro","mago"],"castingTime":"1 a��o","range":"18 m","components":"V, S, M (um diamante de pelo menos 5.000 po)","duration":"Concentra��o, at� 1 minuto","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.ressurreicao_verdadeira','Ressurrei��o Verdadeira',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.ressurreicao_verdadeira","name":"Ressurrei��o Verdadeira","sourcePage":208,"category":"magia","summary":"9� n�vel � necromancia","spellLevel":9,"classIds":["clerigo","druida"],"castingTime":"1 hora","range":"Toque","components":"V, S, M (uma borrifada de �gua benta e diamantes de pelo menos 25.000 po, consumidos)","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.alterar_forma','Alterar Forma',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.alterar_forma","name":"Alterar Forma","sourcePage":209,"category":"magia","summary":"9� n�vel � transmuta��o","spellLevel":9,"classIds":["druida","mago"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S, M (uma coroa de jade de pelo menos 1.500 po)","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.tempestade_da_vinganca','Tempestade da Vingan�a',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.tempestade_da_vinganca","name":"Tempestade da Vingan�a","sourcePage":209,"category":"magia","summary":"9� n�vel � conjura��o","spellLevel":9,"classIds":["druida"],"castingTime":"1 a��o","range":"Vis�o","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Constitui��o"}'::jsonb,'dnd5e'),
('dnd5e.magia.chuva_de_meteoros','Chuva de Meteoros',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.chuva_de_meteoros","name":"Chuva de Meteoros","sourcePage":210,"category":"magia","summary":"9� n�vel � evoca��o","spellLevel":9,"classIds":["feiticeiro","mago"],"castingTime":"1 a��o","range":"1,5 km","components":"V, S","duration":"Instant�nea","savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.desejo','Desejo',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.desejo","name":"Desejo","sourcePage":210,"category":"magia","summary":"9� n�vel � conjura��o","spellLevel":9,"classIds":["feiticeiro","mago"],"castingTime":"1 a��o","range":"Pessoal","components":"V","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.parar_o_tempo','Parar o Tempo',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.parar_o_tempo","name":"Parar o Tempo","sourcePage":210,"category":"magia","summary":"9� n�vel � transmuta��o","spellLevel":9,"classIds":["feiticeiro","mago"],"castingTime":"1 a��o","range":"Pessoal","components":"V","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.encarnacao_fantasmagorica','Encarna��o Fantasmag�rica',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.encarnacao_fantasmagorica","name":"Encarna��o Fantasmag�rica","sourcePage":211,"category":"magia","summary":"9� n�vel � ilus�o","spellLevel":9,"classIds":["mago"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.muralha_prismatica','Muralha Prism�tica',9,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.muralha_prismatica","name":"Muralha Prism�tica","sourcePage":211,"category":"magia","summary":"9� n�vel � abjura��o","spellLevel":9,"classIds":["mago"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"10 minutos","savingThrow":"Destreza"}'::jsonb,'dnd5e')
on conflict (id) do update set name_pt=excluded.name_pt,rank=excluded.rank,is_cantrip=excluded.is_cantrip,is_focus=excluded.is_focus,ruleset=excluded.ruleset,source_book=excluded.source_book,source_page=excluded.source_page,data=excluded.data,system_id=excluded.system_id,updated_at=now();
commit;
