-- Armas mágicas específicas da Tabela de Armas Específicas do Tormenta20 — p. 329.
insert into public.catalog_items (id,name_pt,item_category,ruleset,source_book,source_page,data,system_id) values
('t20.arma_magica.azagaia_relampagos','Azagaia dos relâmpagos','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.azagaia_relampagos","name":"Azagaia dos relâmpagos","sourcePage":329,"category":"arma","summary":"Azagaia específica que descarrega um relâmpago contra o alvo.","magical":true,"magicCategory":"especifica","cost":"T$ 15.000","magicEffects":["Pode ser arremessada como um relâmpago; o efeito retorna ao portador após o ataque."]}'::jsonb,'t20'),
('t20.arma_magica.espada_baronial','Espada baronial','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.espada_baronial","name":"Espada baronial","sourcePage":329,"category":"arma","summary":"Espada específica associada à autoridade de um barão.","magical":true,"magicCategory":"especifica","cost":"T$ 15.000","magicEffects":["Concede prestígio e autoridade; seus bônus se aplicam em interações de comando."]}'::jsonb,'t20'),
('t20.arma_magica.lamina_luz','Lâmina da luz','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.lamina_luz","name":"Lâmina da luz","sourcePage":329,"category":"arma","summary":"Lâmina que emite luz e fere criaturas vulneráveis à luz.","magical":true,"magicCategory":"especifica","cost":"T$ 20.000","magicEffects":["Emite luz; seus ataques causam dano de luz adicional contra alvos apropriados."]}'::jsonb,'t20'),
('t20.arma_magica.lanca_animalesca','Lança animalesca','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.lanca_animalesca","name":"Lança animalesca","sourcePage":329,"category":"arma","summary":"Lança específica ligada ao poder dos animais.","magical":true,"magicCategory":"especifica","cost":"T$ 20.000","magicEffects":["Concede benefícios em testes e ataques relacionados a animais e natureza."]}'::jsonb,'t20'),
('t20.arma_magica.maca_terror','Maça do terror','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.maca_terror","name":"Maça do terror","sourcePage":329,"category":"arma","summary":"Maça que espalha medo entre os inimigos.","magical":true,"magicCategory":"especifica","cost":"T$ 20.000","magicEffects":["Ao acertar, pode deixar o alvo abalado ou amedrontado conforme a resistência aplicável."]}'::jsonb,'t20'),
('t20.arma_magica.florete_fugaz','Florete fugaz','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.florete_fugaz","name":"Florete fugaz","sourcePage":329,"category":"arma","summary":"Florete veloz que favorece ataques e reposicionamento.","magical":true,"magicCategory":"especifica","cost":"T$ 25.000","magicEffects":["Concede velocidade sobrenatural e uma oportunidade extra de reposicionamento por cena."]}'::jsonb,'t20'),
('t20.arma_magica.cajado_destruicao','Cajado da destruição','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.cajado_destruicao","name":"Cajado da destruição","sourcePage":329,"category":"arma","summary":"Cajado carregado de energia destrutiva.","magical":true,"magicCategory":"especifica","cost":"T$ 30.000","magicEffects":["Amplia magias ofensivas e pode liberar uma descarga destrutiva."]}'::jsonb,'t20'),
('t20.arma_magica.cajado_vida','Cajado da vida','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.cajado_vida","name":"Cajado da vida","sourcePage":329,"category":"arma","summary":"Cajado que canaliza energia vital.","magical":true,"magicCategory":"especifica","cost":"T$ 30.000","magicEffects":["Amplia efeitos de cura e pode restaurar vitalidade ao ser empunhado."]}'::jsonb,'t20'),
('t20.arma_magica.machado_silvestre','Machado silvestre','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.machado_silvestre","name":"Machado silvestre","sourcePage":329,"category":"arma","summary":"Machado específico forjado para a vida selvagem.","magical":true,"magicCategory":"especifica","cost":"T$ 35.000","magicEffects":["Concede benefícios contra ameaças naturais e em terrenos selvagens."]}'::jsonb,'t20'),
('t20.arma_magica.martelo_doherimm','Martelo de Doherimm','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.martelo_doherimm","name":"Martelo de Doherimm","sourcePage":329,"category":"arma","summary":"Martelo lendário ligado aos anões de Doherimm.","magical":true,"magicCategory":"especifica","cost":"T$ 35.000","magicEffects":["Concede benefícios de combate e reconhecimento a portadores anões e aliados de Doherimm."]}'::jsonb,'t20'),
('t20.arma_magica.arco_poder','Arco do poder','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.arco_poder","name":"Arco do poder","sourcePage":329,"category":"arma","summary":"Arco específico que concentra força nos disparos.","magical":true,"magicCategory":"especifica","cost":"T$ 45.000","magicEffects":["Aumenta o dano e o alcance efetivo dos disparos."]}'::jsonb,'t20'),
('t20.arma_magica.lingua_deserto','Língua do deserto','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.lingua_deserto","name":"Língua do deserto","sourcePage":329,"category":"arma","summary":"Arma específica associada às areias e ao calor.","magical":true,"magicCategory":"especifica","cost":"T$ 45.000","magicEffects":["Concede benefícios em ambientes áridos e causa efeito elemental de calor nos ataques."]}'::jsonb,'t20'),
('t20.arma_magica.besta_explosiva','Besta explosiva','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.besta_explosiva","name":"Besta explosiva","sourcePage":329,"category":"arma","summary":"Besta cujos virotes explodem ao atingir o alvo.","magical":true,"magicCategory":"especifica","cost":"T$ 50.000","magicEffects":["Disparos causam explosão de área ao atingir, afetando criaturas próximas."]}'::jsonb,'t20'),
('t20.arma_magica.punhal_sszzaazita','Punhal sszzaazita','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.punhal_sszzaazita","name":"Punhal sszzaazita","sourcePage":329,"category":"arma","summary":"Punhal específico associado a venenos e intriga.","magical":true,"magicCategory":"especifica","cost":"T$ 50.000","magicEffects":["Aprimora ataques furtivos e efeitos de veneno aplicados pelo portador."]}'::jsonb,'t20'),
('t20.arma_magica.espada_sortuda','Espada sortuda','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.espada_sortuda","name":"Espada sortuda","sourcePage":329,"category":"arma","summary":"Espada que dobra a sorte de seu portador.","magical":true,"magicCategory":"especifica","cost":"T$ 55.000","magicEffects":["Permite repetir ou melhorar um resultado desfavorável em momentos decisivos."]}'::jsonb,'t20'),
('t20.arma_magica.avalanche','Avalanche','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.avalanche","name":"Avalanche","sourcePage":329,"category":"arma","summary":"Arma específica de impacto devastador.","magical":true,"magicCategory":"especifica","cost":"T$ 70.000","magicEffects":["Seus golpes podem derrubar e atingir mais de um alvo em uma área curta."]}'::jsonb,'t20'),
('t20.arma_magica.cajado_poder','Cajado do poder','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.cajado_poder","name":"Cajado do poder","sourcePage":329,"category":"arma","summary":"Cajado supremo para conjuradores poderosos.","magical":true,"magicCategory":"especifica","cost":"T$ 90.000","magicEffects":["Aumenta a força das magias e armazena cargas para efeitos extraordinários."]}'::jsonb,'t20'),
('t20.arma_magica.vingadora_sagrada','Vingadora sagrada','weapon','padrao','Tormenta20 — Livro Básico',329,'{"id":"t20.arma_magica.vingadora_sagrada","name":"Vingadora sagrada","sourcePage":329,"category":"arma","summary":"Arma sagrada dedicada à luta contra o mal.","magical":true,"magicCategory":"especifica","cost":"T$ 100.000","magicEffects":["Concede bônus contra criaturas malignas e amplia efeitos de aliados sob sua proteção."]}'::jsonb,'t20')
on conflict (id) do update set
  name_pt=excluded.name_pt,
  item_category=excluded.item_category,
  ruleset=excluded.ruleset,
  source_book=excluded.source_book,
  source_page=excluded.source_page,
  data=excluded.data,
  system_id=excluded.system_id,
  updated_at=now();
