insert into public.catalog_backgrounds (id, name_pt, trained_skills, ruleset, source_book, source_page, data, system_id)
values
('t20.acolito','Acólito','{religiao,vontade}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.amigo_dos_animais','Amigo dos Animais','{adestramento,sobrevivencia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.amnesico','Amnésico','{}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.aristocrata','Aristocrata','{nobreza,diplomacia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.artesao','Artesão','{oficio,vontade}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.artista','Artista','{atuacao,diplomacia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.assistente_de_laboratorio','Assistente de Laboratório','{misticismo,oficio}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.batedor','Batedor','{furtividade,sobrevivencia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.capanga','Capanga','{luta,intimidacao}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.charlatao','Charlatão','{enganacao,jogatina}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.circense','Circense','{acrobacia,atuacao}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.criminoso','Criminoso','{enganacao,ladinagem}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.curandeiro','Curandeiro','{cura,religiao}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.eremita','Eremita','{misticismo,sobrevivencia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.escravo','Escravo','{fortitude,sobrevivencia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.estudioso','Estudioso','{conhecimento,investigacao}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.fazendeiro','Fazendeiro','{adestramento,atletismo}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.forasteiro','Forasteiro','{sobrevivencia,percepcao}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.gladiador','Gladiador','{atuacao,luta}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.guarda','Guarda','{fortitude,percepcao}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.herdeiro','Herdeiro','{nobreza,vontade}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.heroi_campones','Herói Camponês','{atletismo,sobrevivencia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.marujo','Marujo','{atletismo,pilotagem}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.mateiro','Mateiro','{furtividade,sobrevivencia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.membro_de_guilda','Membro de Guilda','{diplomacia,oficio}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.mercador','Mercador','{diplomacia,jogatina}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.minerador','Minerador','{atletismo,fortitude}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.nomade','Nômade','{cavalgar,sobrevivencia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.pivete','Pivete','{furtividade,ladinagem}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.refugiado','Refugiado','{intuicao,sobrevivencia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.seguidor','Seguidor','{diplomacia,religiao}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.selvagem','Selvagem','{atletismo,sobrevivencia}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.soldado','Soldado','{guerra,luta}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.taverneiro','Taverneiro','{diplomacia,oficio}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('t20.trabalhador','Trabalhador','{atletismo,oficio}','padrao','Tormenta20 — Livro Básico',93,'{"kind":"origem"}'::jsonb,'t20'),
('dnd5e.acolito','Acólito','{intuicao,religiao}','standard','D&D 5e — Livro do Jogador (2014)',129,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.artesao_guilda','Artesão de Guilda','{intuicao,persuasao}','standard','D&D 5e — Livro do Jogador (2014)',130,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.artista','Artista','{acrobacia,atuacao}','standard','D&D 5e — Livro do Jogador (2014)',134,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.charlatao','Charlatão','{enganacao,prestidigitacao}','standard','D&D 5e — Livro do Jogador (2014)',136,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.criminoso','Criminoso','{furtividade,enganacao}','standard','D&D 5e — Livro do Jogador (2014)',139,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.eremita','Eremita','{medicina,religiao}','standard','D&D 5e — Livro do Jogador (2014)',141,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.heroi_do_povo','Herói do Povo','{adestramento,sobrevivencia}','standard','D&D 5e — Livro do Jogador (2014)',143,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.marinheiro','Marinheiro','{atletismo,percepcao}','standard','D&D 5e — Livro do Jogador (2014)',146,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.nobre','Nobre','{historia,persuasao}','standard','D&D 5e — Livro do Jogador (2014)',147,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.orfao','Órfão','{furtividade,prestidigitacao}','standard','D&D 5e — Livro do Jogador (2014)',150,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.forasteiro','Forasteiro','{atletismo,sobrevivencia}','standard','D&D 5e — Livro do Jogador (2014)',148,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.sabio','Sábio','{arcanismo,historia}','standard','D&D 5e — Livro do Jogador (2014)',152,'{"kind":"background"}'::jsonb,'dnd5e'),
('dnd5e.soldado','Soldado','{atletismo,intimidacao}','standard','D&D 5e — Livro do Jogador (2014)',153,'{"kind":"background"}'::jsonb,'dnd5e')
on conflict (id) do update set name_pt=excluded.name_pt, trained_skills=excluded.trained_skills, ruleset=excluded.ruleset, source_book=excluded.source_book, source_page=excluded.source_page, data=excluded.data, system_id=excluded.system_id, updated_at=now();
