-- Itens mágicos essenciais do Tormenta20 — Livro Básico, pp. 334–335.
-- O catálogo local e o catálogo remoto compartilham os mesmos IDs e metadados.
insert into public.catalog_items (id,name_pt,item_category,ruleset,source_book,source_page,data,system_id) values
('t20.item_magico.anel_protecao','Anel da proteção','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.anel_protecao","name":"Anel da proteção","sourcePage":334,"category":"equipamento","summary":"Anel mágico que protege seu portador.","magical":true,"magicCategory":"menor","cost":"T$ 3.000","magicEffects":["+1 na Defesa."]}'::jsonb,'t20'),
('t20.item_magico.manto_resistencia','Manto da resistência','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.manto_resistencia","name":"Manto da resistência","sourcePage":334,"category":"equipamento","summary":"Manto que ampara contra perigos mágicos.","magical":true,"magicCategory":"menor","cost":"T$ 1.500","magicEffects":["+1 em Fortitude, Reflexos e Vontade."]}'::jsonb,'t20'),
('t20.item_magico.mochila_carga','Mochila de carga','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.mochila_carga","name":"Mochila de carga","sourcePage":334,"category":"equipamento","summary":"Mochila extradimensional para transportar carga.","magical":true,"magicCategory":"menor","cost":"T$ 1.000","magicEffects":["Aumenta a capacidade de carga sem aumentar o peso carregado."]}'::jsonb,'t20'),
('t20.item_magico.corda_escalada','Corda da escalada','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.corda_escalada","name":"Corda da escalada","sourcePage":334,"category":"equipamento","summary":"Corda mágica que auxilia escaladas.","magical":true,"magicCategory":"menor","cost":"T$ 1.000","magicEffects":["Concede +5 em Atletismo para escalar com ela."]}'::jsonb,'t20'),
('t20.item_magico.luvas_delicadeza','Luvas da delicadeza','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.luvas_delicadeza","name":"Luvas da delicadeza","sourcePage":334,"category":"equipamento","summary":"Luvas que favorecem movimentos precisos.","magical":true,"magicCategory":"menor","cost":"T$ 1.500","magicEffects":["Concede +2 em Ladinagem e testes para manipular objetos delicados."]}'::jsonb,'t20'),
('t20.item_magico.manoplas_forca_ogro','Manoplas da força do ogro','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.manoplas_forca_ogro","name":"Manoplas da força do ogro","sourcePage":334,"category":"equipamento","summary":"Manoplas que ampliam a força física.","magical":true,"magicCategory":"menor","cost":"T$ 1.500","magicEffects":["Concede +2 em Força."]}'::jsonb,'t20'),
('t20.item_magico.pingente_sensatez','Pingente da sensatez','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.pingente_sensatez","name":"Pingente da sensatez","sourcePage":334,"category":"equipamento","summary":"Pingente que fortalece a mente.","magical":true,"magicCategory":"menor","cost":"T$ 1.500","magicEffects":["Concede +2 em Sabedoria."]}'::jsonb,'t20'),
('t20.item_magico.torque_vigor','Torque do vigor','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.torque_vigor","name":"Torque do vigor","sourcePage":334,"category":"equipamento","summary":"Torque que reforça a constituição.","magical":true,"magicCategory":"menor","cost":"T$ 1.500","magicEffects":["Concede +2 em Constituição."]}'::jsonb,'t20'),
('t20.item_magico.chapeu_disfarce','Chapéu do disfarce','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.chapeu_disfarce","name":"Chapéu do disfarce","sourcePage":334,"category":"equipamento","summary":"Chapéu que facilita assumir outra aparência.","magical":true,"magicCategory":"menor","cost":"T$ 2.000","magicEffects":["Concede +5 em Enganação para disfarces."]}'::jsonb,'t20'),
('t20.item_magico.anel_escudo_mental','Anel do escudo mental','treasure','padrao','Tormenta20 — Livro Básico',334,'{"id":"t20.item_magico.anel_escudo_mental","name":"Anel do escudo mental","sourcePage":334,"category":"equipamento","summary":"Anel que protege pensamentos e emoções.","magical":true,"magicCategory":"menor","cost":"T$ 3.000","magicEffects":["Concede resistência a efeitos de encantamento e leitura mental."]}'::jsonb,'t20'),
('t20.item_magico.botas_aladas','Botas aladas','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.botas_aladas","name":"Botas aladas","sourcePage":335,"category":"equipamento","summary":"Botas que permitem voar por breves períodos.","magical":true,"magicCategory":"medio","cost":"T$ 5.000","magicEffects":["Permitem voar por até 1 hora por dia, dividida em usos de 10 minutos."]}'::jsonb,'t20'),
('t20.item_magico.anel_invisibilidade','Anel de invisibilidade','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.anel_invisibilidade","name":"Anel de invisibilidade","sourcePage":335,"category":"equipamento","summary":"Anel que oculta o usuário da visão.","magical":true,"magicCategory":"medio","cost":"T$ 7.000","magicEffects":["Concede invisibilidade enquanto ativado; termina ao atacar ou usar uma habilidade ofensiva."]}'::jsonb,'t20'),
('t20.item_magico.manto_aranha','Manto da aranha','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.manto_aranha","name":"Manto da aranha","sourcePage":335,"category":"equipamento","summary":"Manto que concede mobilidade de aranha.","magical":true,"magicCategory":"medio","cost":"T$ 7.000","magicEffects":["Concede deslocamento de escalada e permite lançar teia como uma aranha."]}'::jsonb,'t20'),
('t20.item_magico.cinto_forca_gigante','Cinto da força do gigante','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.cinto_forca_gigante","name":"Cinto da força do gigante","sourcePage":335,"category":"equipamento","summary":"Cinto que torna o portador excepcionalmente forte.","magical":true,"magicCategory":"medio","cost":"T$ 8.500","magicEffects":["Concede +5 em Força."]}'::jsonb,'t20'),
('t20.item_magico.coroa_majestosa','Coroa majestosa','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.coroa_majestosa","name":"Coroa majestosa","sourcePage":335,"category":"equipamento","summary":"Coroa que impõe respeito e autoridade.","magical":true,"magicCategory":"medio","cost":"T$ 8.500","magicEffects":["Concede +5 em Diplomacia e Intimidação."]}'::jsonb,'t20'),
('t20.item_magico.vassoura_voadora','Vassoura voadora','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.vassoura_voadora","name":"Vassoura voadora","sourcePage":335,"category":"equipamento","summary":"Vassoura mágica usada como montaria aérea.","magical":true,"magicCategory":"medio","cost":"T$ 7.000","magicEffects":["Concede deslocamento de voo para uma criatura que a monte."]}'::jsonb,'t20'),
('t20.item_magico.elmo_teletransporte','Elmo do teletransporte','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.elmo_teletransporte","name":"Elmo do teletransporte","sourcePage":335,"category":"equipamento","summary":"Elmo que permite desaparecer e reaparecer a distância.","magical":true,"magicCategory":"maior","cost":"T$ 10.000","magicEffects":["Permite lançar Teletransporte uma vez por dia."]}'::jsonb,'t20'),
('t20.item_magico.tiara_sapiencia','Tiara da sapiência','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.tiara_sapiencia","name":"Tiara da sapiência","sourcePage":335,"category":"equipamento","summary":"Tiara que amplia o intelecto e a percepção.","magical":true,"magicCategory":"medio","cost":"T$ 8.500","magicEffects":["Concede +2 em Inteligência."]}'::jsonb,'t20'),
('t20.item_magico.colar_guardiao','Colar guardião','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.colar_guardiao","name":"Colar guardião","sourcePage":335,"category":"equipamento","summary":"Colar protetor que reforça a Defesa.","magical":true,"magicCategory":"maior","cost":"T$ 17.000","magicEffects":["Concede +5 na Defesa."]}'::jsonb,'t20'),
('t20.item_magico.anel_regeneracao','Anel da regeneração','treasure','padrao','Tormenta20 — Livro Básico',335,'{"id":"t20.item_magico.anel_regeneracao","name":"Anel da regeneração","sourcePage":335,"category":"equipamento","summary":"Anel que restaura ferimentos continuamente.","magical":true,"magicCategory":"maior","cost":"T$ 50.000","magicEffects":["Recupera 1 PV por rodada; não funciona enquanto o portador estiver morrendo."]}'::jsonb,'t20')
on conflict (id) do update set
  name_pt=excluded.name_pt,
  item_category=excluded.item_category,
  ruleset=excluded.ruleset,
  source_book=excluded.source_book,
  source_page=excluded.source_page,
  data=excluded.data,
  system_id=excluded.system_id,
  updated_at=now();
