-- Core actions and conditions for the multi-system compendium.
-- The rows are scoped by system_id + ruleset and never alter PF2e content.

insert into public.catalog_actions (
  id, system_id, name_pt, name_en, name_es,
  description_pt, description_en, description_es,
  action_cost, action_type, traits, rarity, ruleset,
  source_book, source_page, data
)
select id, system_id, name_pt, name_en, name_es,
       description_pt, description_en, description_es,
       action_cost, action_type, array[]::text[], 'common', ruleset,
       source_book, source_page, data
from jsonb_to_recordset($json$
[
  {"id":"dnd5e.action.attack","system_id":"dnd5e","name_pt":"Atacar","name_en":"Attack","name_es":"Atacar","description_pt":"Faça um ataque corpo a corpo ou à distância usando a ação Ataque.","description_en":"Make a melee or ranged attack using the Attack action.","description_es":"Realiza un ataque cuerpo a cuerpo o a distancia usando la acción Atacar.","action_cost":"1","action_type":"basic","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":192,"data":{"ruleKind":"action"}},
  {"id":"dnd5e.action.dash","system_id":"dnd5e","name_pt":"Disparada","name_en":"Dash","name_es":"Correr","description_pt":"Ganhe movimento adicional igual ao seu deslocamento na rodada.","description_en":"Gain extra movement equal to your speed for the turn.","description_es":"Obtén movimiento adicional igual a tu velocidad durante el turno.","action_cost":"1","action_type":"basic","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":192,"data":{"ruleKind":"action"}},
  {"id":"dnd5e.action.disengage","system_id":"dnd5e","name_pt":"Desengajar","name_en":"Disengage","name_es":"Destrabarse","description_pt":"Seu movimento não provoca ataques de oportunidade pelo restante do turno.","description_en":"Your movement doesn't provoke opportunity attacks for the rest of the turn.","description_es":"Tu movimiento no provoca ataques de oportunidad durante el resto del turno.","action_cost":"1","action_type":"basic","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":192,"data":{"ruleKind":"action"}},
  {"id":"dnd5e.action.dodge","system_id":"dnd5e","name_pt":"Esquivar","name_en":"Dodge","name_es":"Esquivar","description_pt":"Dificulte ataques contra você e favoreça testes de Destreza até o início do seu próximo turno.","description_en":"Impose disadvantage on attacks against you and gain advantage on Dexterity saves until your next turn.","description_es":"Dificulta los ataques contra ti y favorece las salvaciones de Destreza hasta tu próximo turno.","action_cost":"1","action_type":"basic","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":192,"data":{"ruleKind":"action"}},
  {"id":"dnd5e.action.help","system_id":"dnd5e","name_pt":"Ajudar","name_en":"Help","name_es":"Ayudar","description_pt":"Dê vantagem ao próximo teste de um aliado ou ajude um ataque contra uma criatura próxima.","description_en":"Give an ally advantage on a relevant check or help an attack against a nearby creature.","description_es":"Da ventaja a una prueba de un aliado o ayuda un ataque contra una criatura cercana.","action_cost":"1","action_type":"basic","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":192,"data":{"ruleKind":"action"}},
  {"id":"dnd5e.action.hide","system_id":"dnd5e","name_pt":"Esconder-se","name_en":"Hide","name_es":"Esconderse","description_pt":"Faça um teste de Destreza (Furtividade) para tentar ficar oculto.","description_en":"Make a Dexterity (Stealth) check to try to hide.","description_es":"Haz una prueba de Destreza (Sigilo) para intentar ocultarte.","action_cost":"1","action_type":"basic","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":192,"data":{"ruleKind":"action"}},
  {"id":"dnd5e.action.ready","system_id":"dnd5e","name_pt":"Preparar","name_en":"Ready","name_es":"Preparar","description_pt":"Defina um gatilho e uma reação para executar uma ação depois.","description_en":"Choose a trigger and a reaction to perform an action later.","description_es":"Elige un desencadenante y una reacción para realizar una acción después.","action_cost":"1","action_type":"basic","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":193,"data":{"ruleKind":"action"}},
  {"id":"dnd5e.action.search","system_id":"dnd5e","name_pt":"Procurar","name_en":"Search","name_es":"Buscar","description_pt":"Dedique sua ação a procurar algo usando um teste apropriado.","description_en":"Devote your action to searching using an appropriate check.","description_es":"Dedica tu acción a buscar usando la prueba apropiada.","action_cost":"1","action_type":"basic","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":193,"data":{"ruleKind":"action"}},
  {"id":"t20.action.attack","system_id":"t20","name_pt":"Ataque","name_en":"Attack","name_es":"Ataque","description_pt":"Faça um ataque com uma arma, ataque desarmado ou magia que use uma ação padrão.","description_en":"Make an attack with a weapon, unarmed attack, or spell that uses a standard action.","description_es":"Realiza un ataque con un arma, ataque desarmado o magia que use una acción estándar.","action_cost":"padrao","action_type":"basic","ruleset":"padrao","source_book":"Tormenta20 — Livro Básico","source_page":221,"data":{"ruleKind":"action"}},
  {"id":"t20.action.move","system_id":"t20","name_pt":"Movimento","name_en":"Movement","name_es":"Movimiento","description_pt":"Mova-se até seu deslocamento usando uma ação de movimento.","description_en":"Move up to your speed using a movement action.","description_es":"Muévete hasta tu velocidad usando una acción de movimiento.","action_cost":"movimento","action_type":"basic","ruleset":"padrao","source_book":"Tormenta20 — Livro Básico","source_page":221,"data":{"ruleKind":"action"}},
  {"id":"t20.action.full_round","system_id":"t20","name_pt":"Ação completa","name_en":"Full action","name_es":"Acción completa","description_pt":"Use sua ação padrão e sua ação de movimento em uma atividade única.","description_en":"Use your standard and movement actions in one activity.","description_es":"Usa tus acciones estándar y de movimiento en una sola actividad.","action_cost":"completa","action_type":"basic","ruleset":"padrao","source_book":"Tormenta20 — Livro Básico","source_page":221,"data":{"ruleKind":"action"}},
  {"id":"t20.action.reaction","system_id":"t20","name_pt":"Reação","name_en":"Reaction","name_es":"Reacción","description_pt":"Responda a um gatilho definido por uma habilidade ou regra.","description_en":"Respond to a trigger defined by an ability or rule.","description_es":"Responde a un desencadenante definido por una habilidad o regla.","action_cost":"reacao","action_type":"basic","ruleset":"padrao","source_book":"Tormenta20 — Livro Básico","source_page":221,"data":{"ruleKind":"action"}},
  {"id":"ose.action.attack","system_id":"ose","name_pt":"Ataque","name_en":"Attack","name_es":"Ataque","description_pt":"Faça uma jogada de ataque usando a tabela e o modificador do personagem.","description_en":"Make an attack roll using the character's table and modifier.","description_es":"Realiza una tirada de ataque usando la tabla y el modificador del personaje.","action_cost":"1","action_type":"basic","ruleset":"advanced","source_book":"Old-School Essentials — Livro de Regras","source_page":60,"data":{"ruleKind":"action"}},
  {"id":"ose.action.move","system_id":"ose","name_pt":"Movimento","name_en":"Movement","name_es":"Movimiento","description_pt":"Mova-se até o valor de movimento da ficha durante a rodada.","description_en":"Move up to the movement value on the character sheet during the round.","description_es":"Muévete hasta el valor de movimiento de la ficha durante la ronda.","action_cost":"1","action_type":"basic","ruleset":"advanced","source_book":"Old-School Essentials — Livro de Regras","source_page":60,"data":{"ruleKind":"action"}},
  {"id":"ose.action.retreat","system_id":"ose","name_pt":"Retirada","name_en":"Retreat","name_es":"Retirada","description_pt":"Recuar de um combate exige seguir a regra de retirada e o risco de perseguição.","description_en":"Withdrawing from combat follows the retreat rule and its pursuit risk.","description_es":"Retirarse del combate sigue la regla de retirada y el riesgo de persecución.","action_cost":"1","action_type":"exploration","ruleset":"advanced","source_book":"Old-School Essentials — Livro de Regras","source_page":60,"data":{"ruleKind":"action"}},
  {"id":"ose.action.cast","system_id":"ose","name_pt":"Conjurar magia","name_en":"Cast a spell","name_es":"Lanzar un conjuro","description_pt":"Conjure uma magia preparada respeitando tempo, alcance e interrupções.","description_en":"Cast a prepared spell respecting its time, range, and interruptions.","description_es":"Lanza un conjuro preparado respetando tiempo, alcance e interrupciones.","action_cost":"1","action_type":"basic","ruleset":"advanced","source_book":"Old-School Essentials — Livro de Regras","source_page":60,"data":{"ruleKind":"action"}}
]$json$::jsonb) as rows(
  id text, system_id text, name_pt text, name_en text, name_es text,
  description_pt text, description_en text, description_es text,
  action_cost text, action_type text, ruleset text,
  source_book text, source_page smallint, data jsonb
)
on conflict (id) do update set
  system_id = excluded.system_id,
  name_pt = excluded.name_pt,
  name_en = excluded.name_en,
  name_es = excluded.name_es,
  description_pt = excluded.description_pt,
  description_en = excluded.description_en,
  description_es = excluded.description_es,
  action_cost = excluded.action_cost,
  action_type = excluded.action_type,
  ruleset = excluded.ruleset,
  source_book = excluded.source_book,
  source_page = excluded.source_page,
  data = excluded.data;

insert into public.catalog_conditions (
  id, system_id, name_pt, name_en, name_es,
  description_pt, description_en, description_es,
  has_value, condition_group, traits, rarity, ruleset,
  source_book, source_page, data
)
select id, system_id, name_pt, name_en, name_es,
       description_pt, description_en, description_es,
       has_value, condition_group, array[]::text[], 'common', ruleset,
       source_book, source_page, data
from jsonb_to_recordset($json$
[
  {"id":"dnd5e.condition.cego","system_id":"dnd5e","name_pt":"Cego","name_en":"Blinded","name_es":"Cegado","description_pt":"Não pode ver; falha automaticamente em testes que dependam da visão. Ataques contra a criatura têm vantagem e seus ataques têm desvantagem.","description_en":"Can't see; automatically fails sight-based checks. Attacks against the creature have advantage and its attacks have disadvantage.","description_es":"No puede ver; falla automáticamente pruebas basadas en la vista. Los ataques contra ella tienen ventaja y sus ataques desventaja.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":290,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.enfeiticado","system_id":"dnd5e","name_pt":"Enfeitiçado","name_en":"Charmed","name_es":"Hechizado","description_pt":"Não pode atacar quem a enfeitiçou nem ter essa criatura como alvo de habilidades nocivas; o enfeitiçador tem vantagem em testes sociais contra ela.","description_en":"Can't attack the charmer or target it with harmful abilities; the charmer has advantage on social checks against it.","description_es":"No puede atacar al hechicero ni hacerle objetivo de habilidades dañinas; el hechicero tiene ventaja en pruebas sociales.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":290,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.surdo","system_id":"dnd5e","name_pt":"Surdo","name_en":"Deafened","name_es":"Ensordecido","description_pt":"Não pode ouvir e falha automaticamente em testes que dependam da audição.","description_en":"Can't hear and automatically fails checks that require hearing.","description_es":"No puede oír y falla automáticamente pruebas que requieren oído.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":290,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.amedrontado","system_id":"dnd5e","name_pt":"Amedrontado","name_en":"Frightened","name_es":"Asustado","description_pt":"Tem desvantagem em testes e ataques enquanto a fonte do medo estiver no campo de visão e não pode se aproximar voluntariamente dela.","description_en":"Has disadvantage on checks and attacks while the source of fear is in sight and can't willingly move closer to it.","description_es":"Tiene desventaja en pruebas y ataques mientras vea la fuente del miedo y no puede acercarse voluntariamente.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":290,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.agarrado","system_id":"dnd5e","name_pt":"Agarrado","name_en":"Grappled","name_es":"Agarrado","description_pt":"O deslocamento chega a 0 e não recebe bônus de deslocamento; termina quando o agarrador fica incapacitado ou quando a criatura escapa.","description_en":"Speed becomes 0 and can't benefit from speed bonuses; ends when the grappler is incapacitated or the creature escapes.","description_es":"La velocidad es 0 y no se beneficia de bonificaciones; termina cuando el agarrador queda incapacitado o escapa.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":290,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.incapacitado","system_id":"dnd5e","name_pt":"Incapacitado","name_en":"Incapacitated","name_es":"Incapacitado","description_pt":"Não pode realizar ações nem reações.","description_en":"Can't take actions or reactions.","description_es":"No puede realizar acciones ni reacciones.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":290,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.invisivel","system_id":"dnd5e","name_pt":"Invisível","name_en":"Invisible","name_es":"Invisible","description_pt":"Não pode ser vista sem magia ou sentido especial; ataques contra ela têm desvantagem e seus ataques têm vantagem.","description_en":"Can't be seen without magic or special sense; attacks against it have disadvantage and its attacks have advantage.","description_es":"No puede verse sin magia o sentido especial; los ataques contra ella tienen desventaja y sus ataques ventaja.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":291,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.paralisado","system_id":"dnd5e","name_pt":"Paralisado","name_en":"Paralyzed","name_es":"Paralizado","description_pt":"Está incapacitado, não pode se mover ou falar, falha em salvamentos de Força e Destreza e ataques contra ela têm vantagem; ataques próximos que acertem são críticos.","description_en":"Is incapacitated, can't move or speak, automatically fails Strength and Dexterity saves, and attacks against it have advantage; nearby hits are critical hits.","description_es":"Está incapacitado, no puede moverse ni hablar, falla salvaciones de Fuerza y Destreza y los ataques tienen ventaja; los impactos cercanos son críticos.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":291,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.petrificado","system_id":"dnd5e","name_pt":"Petrificado","name_en":"Petrified","name_es":"Petrificado","description_pt":"É transformado em substância inanimada, fica incapacitado, não percebe os arredores e recebe resistência a todo dano.","description_en":"Is transformed into an inanimate substance, is incapacitated, unaware, and has resistance to all damage.","description_es":"Se transforma en sustancia inanimada, queda incapacitado, no percibe el entorno y tiene resistencia a todo daño.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":291,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.envenenado","system_id":"dnd5e","name_pt":"Envenenado","name_en":"Poisoned","name_es":"Envenenado","description_pt":"Tem desvantagem em jogadas de ataque e testes de habilidade.","description_en":"Has disadvantage on attack rolls and ability checks.","description_es":"Tiene desventaja en tiradas de ataque y pruebas de característica.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":292,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.caido","system_id":"dnd5e","name_pt":"Caído","name_en":"Prone","name_es":"Derribado","description_pt":"Só pode rastejar; tem desvantagem em ataques e ataques contra ela têm vantagem a até 1,5 m.","description_en":"Can only crawl; has disadvantage on attacks and attacks against it have advantage within 5 feet.","description_es":"Solo puede gatear; tiene desventaja en ataques y los ataques cercanos tienen ventaja.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":292,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.contido","system_id":"dnd5e","name_pt":"Contido","name_en":"Restrained","name_es":"Restringido","description_pt":"O deslocamento chega a 0; ataques contra ela têm vantagem, seus ataques têm desvantagem e tem desvantagem em salvamentos de Destreza.","description_en":"Speed becomes 0; attacks against it have advantage, its attacks have disadvantage, and it has disadvantage on Dexterity saves.","description_es":"La velocidad es 0; los ataques tienen ventaja, sus ataques desventaja y tiene desventaja en salvaciones de Destreza.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":292,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.atordoado","system_id":"dnd5e","name_pt":"Atordoado","name_en":"Stunned","name_es":"Aturdido","description_pt":"Fica incapacitado, não pode se mover e só fala hesitantemente; falha em salvamentos de Força e Destreza e ataques contra ela têm vantagem.","description_en":"Is incapacitated, can't move, can speak only falteringly, automatically fails Strength and Dexterity saves, and attacks against it have advantage.","description_es":"Está incapacitado, no puede moverse, habla con dificultad, falla salvaciones de Fuerza y Destreza y los ataques tienen ventaja.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":292,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.inconsciente","system_id":"dnd5e","name_pt":"Inconsciente","name_en":"Unconscious","name_es":"Inconsciente","description_pt":"Está incapacitado, não pode se mover ou falar, não percebe o ambiente, falha em salvamentos de Força e Destreza e ataques próximos que acertem são críticos.","description_en":"Is incapacitated, can't move or speak, unaware, automatically fails Strength and Dexterity saves, and nearby hits are critical hits.","description_es":"Está incapacitado, no puede moverse ni hablar, no percibe el entorno, falla salvaciones de Fuerza y Destreza y los impactos cercanos son críticos.","has_value":false,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":292,"data":{"ruleKind":"condition"}},
  {"id":"dnd5e.condition.exausto","system_id":"dnd5e","name_pt":"Exausto","name_en":"Exhaustion","name_es":"Agotamiento","description_pt":"Cada nível impõe -1 cumulativo em testes de habilidade, ataques e salvamentos e reduz o deslocamento em 1,5 m.","description_en":"Each level imposes a cumulative -1 penalty to ability checks, attacks, and saves and reduces speed by 5 feet.","description_es":"Cada nivel impone -1 acumulativo en pruebas, ataques y salvaciones y reduce la velocidad en 5 pies.","has_value":true,"condition_group":"core","ruleset":"standard","source_book":"Livro do Jogador — D&D 5e 2014","source_page":291,"data":{"ruleKind":"condition"}}
]$json$::jsonb) as rows(
  id text, system_id text, name_pt text, name_en text, name_es text,
  description_pt text, description_en text, description_es text,
  has_value boolean, condition_group text, ruleset text,
  source_book text, source_page smallint, data jsonb
)
on conflict (id) do update set
  system_id = excluded.system_id,
  name_pt = excluded.name_pt,
  name_en = excluded.name_en,
  name_es = excluded.name_es,
  description_pt = excluded.description_pt,
  description_en = excluded.description_en,
  description_es = excluded.description_es,
  has_value = excluded.has_value,
  condition_group = excluded.condition_group,
  ruleset = excluded.ruleset,
  source_book = excluded.source_book,
  source_page = excluded.source_page,
  data = excluded.data;
