-- Refresh idempotente das escolhas estruturadas dos poderes T20.
insert into public.catalog_feats (id,feat_type,level,name_pt,ruleset,source_book,source_page,data,system_id) values
('t20.poder.aumento_de_atributo','general',2,'Aumento de Atributo','padrao','Tormenta20 — Livro Básico',82,'{"id":"t20.poder.aumento_de_atributo","name":"Aumento de Atributo","sourcePage":82,"category":"poder","summary":"Aumenta um atributo em +2; escolhas posteriores para o mesmo atributo concedem +1.","powerGroup":"destino","minimumLevel":2,"repeatable":true,"classPower":true,"choices":[{"id":"t20-ability-increase","label":"Atributo","options":["Força","Destreza","Constituição","Inteligência","Sabedoria","Carisma"],"count":1}]}'::jsonb,'t20'),
('t20.poder.orar','general',2,'Orar','padrao','Tormenta20 — Livro Básico',83,'{"id":"t20.poder.orar","name":"Orar","sourcePage":83,"category":"poder","summary":"Aprende e lança uma magia divina de 1º círculo; usa Sabedoria. Pode ser escolhido mais de uma vez.","powerGroup":"magia","minimumLevel":2,"classIds":["paladino"],"repeatable":true,"choices":[{"id":"t20-prayer-spell","label":"Magia divina de 1º círculo","options":["Abençoar Alimentos","Arma Espiritual","Curar Ferimentos","Escudo da Fé","Luz","Orientação","Santuário"],"count":1}]}'::jsonb,'t20'),
('t20.poder.inimigo_de_criatura','general',2,'Inimigo de (Criatura)','padrao','Tormenta20 — Livro Básico',51,'{"id":"t20.poder.inimigo_de_criatura","name":"Inimigo de (Criatura)","sourcePage":51,"category":"poder","summary":"Escolhe tipo de criatura ou raças humanoides; Marca da Presa dobra os dados de dano contra a escolha.","minimumLevel":2,"repeatable":true,"powerGroup":"combate","classIds":["cacador"],"choices":[{"id":"t20-favored-enemy","label":"Inimigo favorecido","options":["Aberração","Animal","Construto","Espírito","Fada","Humanoide","Monstro","Morto-vivo","Planta","Linhagem ou raça humanoide"],"count":1}]}'::jsonb,'t20'),
('t20.poder.forma_selvagem','general',2,'Forma Selvagem','padrao','Tormenta20 — Livro Básico',62,'{"id":"t20.poder.forma_selvagem","name":"Forma Selvagem","sourcePage":62,"category":"poder","summary":"Transforma-se em um tipo de animal; cada escolha concede uma forma diferente.","minimumLevel":2,"repeatable":true,"powerGroup":"magia","classIds":["druida"],"choices":[{"id":"t20-wild-shape","label":"Forma animal","options":["Arapuca","Cão","Cavalo","Gato","Lobo","Morcego","Rato","Sapo","Serpente","Urso"],"count":1}]}'::jsonb,'t20'),
('t20.poder.conhecimento_de_formulas','general',2,'Conhecimento de Fórmulas','padrao','Tormenta20 — Livro Básico',69,'{"id":"t20.poder.conhecimento_de_formulas","name":"Conhecimento de Fórmulas","sourcePage":69,"category":"poder","summary":"Aprende três fórmulas de quaisquer círculos que possa aprender; pode escolher este poder várias vezes.","minimumLevel":2,"prerequisite":"Alquimista Iniciado","repeatable":true,"powerGroup":"destino","classIds":["inventor"],"choices":[{"id":"t20-formulas","label":"Fórmulas","options":["Poção de Cura","Poção de Força","Bomba de Fogo","Bomba de Gelo","Antídoto","Elixir de Resistência"],"count":3}]}'::jsonb,'t20'),
('t20.poder.conhecimento_magico','general',2,'Conhecimento Mágico','padrao','Tormenta20 — Livro Básico',38,'{"id":"t20.poder.conhecimento_magico","name":"Conhecimento Mágico","sourcePage":38,"category":"poder","summary":"Aprende duas magias de qualquer círculo que possa lançar; pode escolher este poder várias vezes.","minimumLevel":2,"repeatable":true,"powerGroup":"magia","classIds":["arcanista"],"choices":[{"id":"t20-known-spells","label":"Magias aprendidas","options":["Amedrontar","Arma Mágica","Bola de Fogo","Curar Ferimentos","Dissipar Magia","Escudo da Fé","Luz","Queda Suave"],"count":2}]}'::jsonb,'t20'),
('t20.poder.especialista_em_escola','general',2,'Especialista em Escola','padrao','Tormenta20 — Livro Básico',38,'{"id":"t20.poder.especialista_em_escola","name":"Especialista em Escola","sourcePage":38,"category":"poder","summary":"Escolhe uma escola de magia; a CD para resistir a magias dessa escola aumenta em +2.","minimumLevel":2,"prerequisite":"Bruxo ou Mago","powerGroup":"magia","classIds":["arcanista"],"choices":[{"id":"t20-magic-school","label":"Escola de magia","options":["Abjuração","Adivinhação","Convocação","Encantamento","Evocação","Ilusão","Necromancia","Transmutação"],"count":1}]}'::jsonb,'t20'),
('t20.poder.familiar','general',2,'Familiar','padrao','Tormenta20 — Livro Básico',38,'{"id":"t20.poder.familiar","name":"Familiar","sourcePage":38,"category":"poder","summary":"Adquire um animal de estimação mágico com benefício escolhido entre as opções de familiar arcano.","minimumLevel":2,"powerGroup":"magia","classIds":["arcanista"],"choices":[{"id":"t20-familiar-benefit","label":"Benefício do familiar","options":["Arapuca","Coruja","Gato","Morcego","Rato","Sapo","Serpente","Víbora"],"count":1}]}'::jsonb,'t20'),
('t20.poder.foco_em_arma','general',1,'Foco em Arma','padrao','Tormenta20 — Livro Básico',134,'{"id":"t20.poder.foco_em_arma","name":"Foco em Arma","sourcePage":134,"category":"poder","summary":"+2 nos ataques com uma arma escolhida; pode ser escolhido novamente para outra arma.","powerGroup":"combate","prerequisite":"Proficiência com a arma","choices":[{"id":"t20-weapon-focus","label":"Arma","options":["Adaga","Espada curta","Espada longa","Machado de guerra","Montante","Arco curto","Besta leve","Lança","Maça","Bordão","Pique","Tacape"],"count":1}]}'::jsonb,'t20'),
('t20.poder.proficiencia','general',1,'Proficiência','padrao','Tormenta20 — Livro Básico',135,'{"id":"t20.poder.proficiencia","name":"Proficiência","sourcePage":135,"category":"poder","summary":"Escolhe e recebe proficiência em armas marciais, armas de fogo, armaduras pesadas ou escudos.","powerGroup":"combate","choices":[{"id":"t20-proficiency","label":"Proficiência","options":["Armas marciais","Armas de fogo","Armaduras pesadas","Escudos"],"count":1}]}'::jsonb,'t20'),
('t20.poder.treinamento_em_pericia','general',1,'Treinamento em Perícia','padrao','Tormenta20 — Livro Básico',136,'{"id":"t20.poder.treinamento_em_pericia","name":"Treinamento em Perícia","sourcePage":136,"category":"poder","summary":"Torna-se treinado em uma perícia escolhida; pode ser escolhido novamente para outra perícia.","powerGroup":"destino","choices":[{"id":"t20-trained-skill","label":"Perícia","options":["Acrobacia","Adestramento","Atletismo","Atuação","Cavalgar","Conhecimento","Cura","Diplomacia","Enganação","Furtividade","Guerra","Iniciativa","Intimidação","Intuição","Investigação","Ladinagem","Luta","Misticismo","Nobreza","Percepção","Pontaria","Religião","Sobrevivência","Vontade","Ofício"],"count":1}]}'::jsonb,'t20')
on conflict (id) do update set feat_type=excluded.feat_type,level=excluded.level,name_pt=excluded.name_pt,ruleset=excluded.ruleset,source_book=excluded.source_book,source_page=excluded.source_page,data=excluded.data,system_id=excluded.system_id,updated_at=now();
