-- D&D 5e Livro do Jogador (2014): n�cleo de magias de 7� n�vel.
begin;
insert into public.catalog_spells (id,name_pt,rank,is_cantrip,is_focus,ruleset,source_book,source_page,data,system_id) values
('dnd5e.magia.dedo_da_morte','Dedo da Morte',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.dedo_da_morte","name":"Dedo da Morte","sourcePage":208,"category":"magia","summary":"7� n�vel � necromancia","spellLevel":7,"classIds":["bruxo","feiticeiro","mago"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"Instant�nea","savingThrow":"Constitui��o"}'::jsonb,'dnd5e'),
('dnd5e.magia.forma_eterea','Forma Et�rea',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.forma_eterea","name":"Forma Et�rea","sourcePage":208,"category":"magia","summary":"7� n�vel � transmuta��o","spellLevel":7,"classIds":["bruxo","clerigo","feiticeiro","mago"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"Concentra��o, at� 8 horas","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.prisao_de_energia','Pris�o de Energia',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.prisao_de_energia","name":"Pris�o de Energia","sourcePage":208,"category":"magia","summary":"7� n�vel � evoca��o","spellLevel":7,"classIds":["bruxo","mago"],"castingTime":"1 a��o","range":"30 m","components":"V, S, M (p� de rubi de 1.500 po)","duration":"1 hora","savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.viagem_planar','Viagem Planar',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.viagem_planar","name":"Viagem Planar","sourcePage":208,"category":"magia","summary":"7� n�vel � conjura��o","spellLevel":7,"classIds":["bruxo","clerigo","druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"Toque","components":"V, S, M (uma haste met�lica bifurcada de pelo menos 250 po, sintonizada com um plano de exist�ncia espec�fico)","duration":"Instant�nea","savingThrow":"Carisma"}'::jsonb,'dnd5e'),
('dnd5e.magia.conjurar_celestial','Conjurar Celestial',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.conjurar_celestial","name":"Conjurar Celestial","sourcePage":208,"category":"magia","summary":"7� n�vel � conjura��o","spellLevel":7,"classIds":["clerigo"],"castingTime":"1 minuto","range":"27 m","components":"V, S","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.palavra_divina','Palavra Divina',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.palavra_divina","name":"Palavra Divina","sourcePage":208,"category":"magia","summary":"7� n�vel � evoca��o","spellLevel":7,"classIds":["clerigo"],"castingTime":"1 a��o b�nus","range":"9 m","components":"V","duration":"Instant�nea","savingThrow":"Carisma"}'::jsonb,'dnd5e'),
('dnd5e.magia.regeneracao','Regenera��o',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.regeneracao","name":"Regenera��o","sourcePage":208,"category":"magia","summary":"7� n�vel � transmuta��o","spellLevel":7,"classIds":["clerigo","druida"],"castingTime":"1 minuto","range":"Toque","components":"V, S, M (uma conta de ora��o e �gua benta)","duration":"1 hora"}'::jsonb,'dnd5e'),
('dnd5e.magia.ressurreicao','Ressurrei��o',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.ressurreicao","name":"Ressurrei��o","sourcePage":208,"category":"magia","summary":"7� n�vel � necromancia","spellLevel":7,"classIds":["clerigo"],"castingTime":"1 hora","range":"Toque","components":"V, S, M (um diamante de pelo menos 1.000 po, consumido)","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.simbolo','S�mbolo',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.simbolo","name":"S�mbolo","sourcePage":208,"category":"magia","summary":"7� n�vel � abjura��o","spellLevel":7,"classIds":["clerigo","mago"],"castingTime":"1 minuto","range":"Toque","components":"V, S, M (merc�rio, f�sforo e p� de diamante e opala, totalizando pelo menos 1.000 po, consumidos)","duration":"At� ser dissipado","savingThrow":"Constitui��o"}'::jsonb,'dnd5e'),
('dnd5e.magia.tempestade_de_fogo','Tempestade de Fogo',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.tempestade_de_fogo","name":"Tempestade de Fogo","sourcePage":208,"category":"magia","summary":"7� n�vel � evoca��o","spellLevel":7,"classIds":["clerigo","druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"45 m","components":"V, S","duration":"Instant�nea","savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.inverter_gravidade','Inverter a Gravidade',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.inverter_gravidade","name":"Inverter a Gravidade","sourcePage":209,"category":"magia","summary":"7� n�vel � transmuta��o","spellLevel":7,"classIds":["druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"30 m","components":"V, S, M (uma magnetita e limalha de ferro)","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.miragem','Miragem',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.miragem","name":"Miragem","sourcePage":209,"category":"magia","summary":"7� n�vel � ilus�o","spellLevel":7,"classIds":["druida","mago"],"castingTime":"10 minutos","range":"Vis�o","components":"V, S","duration":"10 dias"}'::jsonb,'dnd5e'),
('dnd5e.magia.bola_de_fogo_controlavel','Bola de Fogo Control�vel',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.bola_de_fogo_controlavel","name":"Bola de Fogo Control�vel","sourcePage":210,"category":"magia","summary":"7� n�vel � evoca��o","spellLevel":7,"classIds":["feiticeiro","mago"],"castingTime":"1 a��o","range":"45 m","components":"V, S, M (uma pequena bola de guano de morcego e enxofre)","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.rajada_prismatica','Rajada Prism�tica',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.rajada_prismatica","name":"Rajada Prism�tica","sourcePage":210,"category":"magia","summary":"7� n�vel � evoca��o","spellLevel":7,"classIds":["feiticeiro","mago"],"castingTime":"1 a��o","range":"Pessoal (cone de 18 m)","components":"V, S","duration":"Instant�nea","savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.espada_de_mordenkainen','Espada de Mordenkainen',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.espada_de_mordenkainen","name":"Espada de Mordenkainen","sourcePage":211,"category":"magia","summary":"7� n�vel � evoca��o","spellLevel":7,"classIds":["mago"],"castingTime":"1 a��o b�nus","range":"18 m","components":"V, S, M (uma espada de platina em miniatura, com cabo e pomo de cobre e zinco, no valor de 250 po)","duration":"Concentra��o, at� 1 minuto","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.mansao_magnifica_mordenkainen','Mans�o Magn�fica de Mordenkainen',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.mansao_magnifica_mordenkainen","name":"Mans�o Magn�fica de Mordenkainen","sourcePage":211,"category":"magia","summary":"7� n�vel � conjura��o","spellLevel":7,"classIds":["mago"],"castingTime":"1 minuto","range":"90 m","components":"V, S, M (um portal em miniatura esculpido em marfim, um pequeno peda�o de m�rmore polido e uma colher min�scula de prata, cada item valendo pelo menos 5 po)","duration":"24 horas"}'::jsonb,'dnd5e'),
('dnd5e.magia.projetar_imagem','Projetar Imagem',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.projetar_imagem","name":"Projetar Imagem","sourcePage":211,"category":"magia","summary":"7� n�vel � ilus�o","spellLevel":7,"classIds":["mago"],"castingTime":"1 a��o","range":"750 km","components":"V, S, M (uma pequena r�plica sua feita de materiais valendo pelo menos 5 po)","duration":"Concentra��o, at� 1 dia","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.simulacro','Simulacro',7,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.simulacro","name":"Simulacro","sourcePage":211,"category":"magia","summary":"7� n�vel � ilus�o","spellLevel":7,"classIds":["mago"],"castingTime":"12 horas","range":"Toque","components":"V, S, M (neve ou gelo em quantidade suficiente para fazer uma c�pia em tamanho real da criatura duplicada; algum cabelo, peda�o de unha ou outro peda�o do corpo da criatura colocado dentro da neve ou do gelo; e p� de rubi de 1.500 po, polvilhado sobre a duplicata e consumido)","duration":"At� ser dissipado"}'::jsonb,'dnd5e')
on conflict (id) do update set name_pt=excluded.name_pt,rank=excluded.rank,is_cantrip=excluded.is_cantrip,is_focus=excluded.is_focus,ruleset=excluded.ruleset,source_book=excluded.source_book,source_page=excluded.source_page,data=excluded.data,system_id=excluded.system_id,updated_at=now();
commit;
