-- D&D 5e Livro do Jogador (2014): n�cleo adicional de magias de 4� n�vel.
begin;
insert into public.catalog_spells (id,name_pt,rank,is_cantrip,is_focus,ruleset,source_book,source_page,data,system_id) values
('dnd5e.magia.adivinhacao','Adivinha��o',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.adivinhacao","name":"Adivinha��o","sourcePage":208,"category":"magia","summary":"4� n�vel � adivinha��o � ritual","spellLevel":4,"classIds":["clerigo"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S, M (incenso e uma oferenda de pelo menos 25 po, consumidos)","duration":"Instant�nea","ritual":true}'::jsonb,'dnd5e'),
('dnd5e.magia.controlar_a_agua','Controlar a �gua',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.controlar_a_agua","name":"Controlar a �gua","sourcePage":208,"category":"magia","summary":"4� n�vel � transmuta��o","spellLevel":4,"classIds":["clerigo","druida","mago"],"castingTime":"1 a��o","range":"90 m","components":"V, S, M (uma gota de �gua e uma pitada de poeira)","duration":"Concentra��o, at� 10 minutos","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.localizar_criatura','Localizar Criatura',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.localizar_criatura","name":"Localizar Criatura","sourcePage":208,"category":"magia","summary":"4� n�vel � adivinha��o","spellLevel":4,"classIds":["clerigo","druida","mago","paladino","patrulheiro"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S, M (um pouco de pelo de uma criatura)","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.guardiao_da_fe','Guardi�o da F�',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.guardiao_da_fe","name":"Guardi�o da F�","sourcePage":208,"category":"magia","summary":"4� n�vel � conjura��o","spellLevel":4,"classIds":["clerigo"],"castingTime":"1 a��o","range":"9 m","components":"V","duration":"8 horas"}'::jsonb,'dnd5e'),
('dnd5e.magia.moldar_rochas','Moldar Rochas',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.moldar_rochas","name":"Moldar Rochas","sourcePage":208,"category":"magia","summary":"4� n�vel � transmuta��o","spellLevel":4,"classIds":["clerigo","druida","mago"],"castingTime":"1 a��o","range":"Toque","components":"V, S, M (argila macia, que deve ser trabalhada at� assumir a forma desejada)","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.movimentacao_livre','Movimenta��o Livre',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.movimentacao_livre","name":"Movimenta��o Livre","sourcePage":208,"category":"magia","summary":"4� n�vel � abjura��o","spellLevel":4,"classIds":["clerigo","druida","paladino","patrulheiro"],"castingTime":"1 a��o","range":"Toque","components":"V, S, M (uma tira de couro enrolada)","duration":"1 hora"}'::jsonb,'dnd5e'),
('dnd5e.magia.protecao_contra_morte','Prote��o contra a Morte',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',208,'{"id":"dnd5e.magia.protecao_contra_morte","name":"Prote��o contra a Morte","sourcePage":208,"category":"magia","summary":"4� n�vel � abjura��o","spellLevel":4,"classIds":["clerigo","paladino"],"castingTime":"1 a��o","range":"Toque","components":"V, S","duration":"8 horas"}'::jsonb,'dnd5e'),
('dnd5e.magia.confusao','Confus�o',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.confusao","name":"Confus�o","sourcePage":209,"category":"magia","summary":"4� n�vel � encantamento","spellLevel":4,"classIds":["druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"27 m","components":"V, S, M (tr�s cascas de noz)","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.conjurar_elementais_menores','Conjurar Elementais Menores',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.conjurar_elementais_menores","name":"Conjurar Elementais Menores","sourcePage":209,"category":"magia","summary":"4� n�vel � conjura��o","spellLevel":4,"classIds":["druida","mago"],"castingTime":"1 minuto","range":"27 m","components":"V, S","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.conjurar_seres_floresta','Conjurar Seres da Floresta',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.conjurar_seres_floresta","name":"Conjurar Seres da Floresta","sourcePage":209,"category":"magia","summary":"4� n�vel � conjura��o","spellLevel":4,"classIds":["druida","patrulheiro"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.dominar_besta','Dominar Besta',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.dominar_besta","name":"Dominar Besta","sourcePage":209,"category":"magia","summary":"4� n�vel � encantamento","spellLevel":4,"classIds":["druida","feiticeiro"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.inseto_gigante','Inseto Gigante',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.inseto_gigante","name":"Inseto Gigante","sourcePage":209,"category":"magia","summary":"4� n�vel � transmuta��o","spellLevel":4,"classIds":["druida"],"castingTime":"1 a��o","range":"18 m","components":"V, S","duration":"Concentra��o, at� 10 minutos","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.malogro','Malogro',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.malogro","name":"Malogro","sourcePage":209,"category":"magia","summary":"4� n�vel � necromancia","spellLevel":4,"classIds":["druida","feiticeiro","mago","bruxo"],"castingTime":"1 a��o","range":"9 m","components":"V, S","duration":"Instant�nea","savingThrow":"Constitui��o"}'::jsonb,'dnd5e'),
('dnd5e.magia.metamorfose','Metamorfose',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.metamorfose","name":"Metamorfose","sourcePage":209,"category":"magia","summary":"4� n�vel � transmuta��o","spellLevel":4,"classIds":["druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"18 m","components":"V, S, M (um casulo de lagarta)","duration":"Concentra��o, at� 1 hora","concentration":true,"savingThrow":"Sabedoria"}'::jsonb,'dnd5e'),
('dnd5e.magia.pele_de_pedra','Pele de Pedra',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.pele_de_pedra","name":"Pele de Pedra","sourcePage":209,"category":"magia","summary":"4� n�vel � abjura��o","spellLevel":4,"classIds":["druida","feiticeiro","mago","patrulheiro"],"castingTime":"1 a��o","range":"Toque","components":"V, S, M (p� de diamante de 100 po, consumido)","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.tempestade_de_gelo','Tempestade de Gelo',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.tempestade_de_gelo","name":"Tempestade de Gelo","sourcePage":209,"category":"magia","summary":"4� n�vel � evoca��o","spellLevel":4,"classIds":["druida","feiticeiro","mago"],"castingTime":"1 a��o","range":"90 m","components":"V, S, M (uma pitada de poeira e algumas gotas de �gua)","duration":"Instant�nea","savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.terreno_alucinogeno','Terreno Alucin�geno',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.terreno_alucinogeno","name":"Terreno Alucin�geno","sourcePage":209,"category":"magia","summary":"4� n�vel � ilus�o","spellLevel":4,"classIds":["druida","mago"],"castingTime":"10 minutos","range":"90 m","components":"V, S, M (uma pedra, um galho e um pouco de �gua)","duration":"24 horas"}'::jsonb,'dnd5e'),
('dnd5e.magia.vinha_esmagadora','Vinha Esmagadora',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',209,'{"id":"dnd5e.magia.vinha_esmagadora","name":"Vinha Esmagadora","sourcePage":209,"category":"magia","summary":"4� n�vel � conjura��o","spellLevel":4,"classIds":["druida","patrulheiro"],"castingTime":"1 a��o b�nus","range":"18 m","components":"V, S","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.porta_dimensional','Porta Dimensional',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',210,'{"id":"dnd5e.magia.porta_dimensional","name":"Porta Dimensional","sourcePage":210,"category":"magia","summary":"4� n�vel � conjura��o","spellLevel":4,"classIds":["feiticeiro","mago","bruxo"],"castingTime":"1 a��o","range":"150 m","components":"V","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.escudo_de_fogo','Escudo de Fogo',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.escudo_de_fogo","name":"Escudo de Fogo","sourcePage":211,"category":"magia","summary":"4� n�vel � evoca��o","spellLevel":4,"classIds":["mago"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S, M (um pouco de f�sforo ou um vaga-lume)","duration":"10 minutos"}'::jsonb,'dnd5e'),
('dnd5e.magia.esfera_resiliente_otiluke','Esfera Resiliente de Otiluke',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.esfera_resiliente_otiluke","name":"Esfera Resiliente de Otiluke","sourcePage":211,"category":"magia","summary":"4� n�vel � evoca��o","spellLevel":4,"classIds":["mago"],"castingTime":"1 a��o","range":"9 m","components":"V, S, M (uma esfera de cristal e uma hemisfera de goma ar�bica)","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.fabricar','Fabricar',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.fabricar","name":"Fabricar","sourcePage":211,"category":"magia","summary":"4� n�vel � transmuta��o","spellLevel":4,"classIds":["mago"],"castingTime":"10 minutos","range":"36 m","components":"V, S","duration":"Instant�nea"}'::jsonb,'dnd5e'),
('dnd5e.magia.olho_arcano','Olho Arcano',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.olho_arcano","name":"Olho Arcano","sourcePage":211,"category":"magia","summary":"4� n�vel � adivinha��o","spellLevel":4,"classIds":["mago"],"castingTime":"1 a��o","range":"9 m","components":"V, S, M (um pouco de pelo de morcego)","duration":"Concentra��o, at� 1 hora","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.tentaculos_negros_evard','Tent�culos Negros de Evard',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',211,'{"id":"dnd5e.magia.tentaculos_negros_evard","name":"Tent�culos Negros de Evard","sourcePage":211,"category":"magia","summary":"4� n�vel � conjura��o","spellLevel":4,"classIds":["mago"],"castingTime":"1 a��o","range":"27 m","components":"V, S, M (um peda�o de tent�culo de um polvo ou lula gigante)","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Destreza"}'::jsonb,'dnd5e'),
('dnd5e.magia.aura_de_pureza','Aura de Pureza',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',212,'{"id":"dnd5e.magia.aura_de_pureza","name":"Aura de Pureza","sourcePage":212,"category":"magia","summary":"4� n�vel � abjura��o","spellLevel":4,"classIds":["paladino"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"Concentra��o, at� 10 minutos","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.aura_de_vida','Aura de Vida',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',212,'{"id":"dnd5e.magia.aura_de_vida","name":"Aura de Vida","sourcePage":212,"category":"magia","summary":"4� n�vel � abjura��o","spellLevel":4,"classIds":["paladino"],"castingTime":"1 a��o","range":"Pessoal","components":"V, S","duration":"Concentra��o, at� 10 minutos","concentration":true}'::jsonb,'dnd5e'),
('dnd5e.magia.destruicao_estonteante','Destrui��o Estonteante',4,FALSE,FALSE,'standard','D&D 5e � Livro do Jogador (2014)',212,'{"id":"dnd5e.magia.destruicao_estonteante","name":"Destrui��o Estonteante","sourcePage":212,"category":"magia","summary":"4� n�vel � evoca��o","spellLevel":4,"classIds":["paladino"],"castingTime":"1 a��o b�nus","range":"Pessoal","components":"V","duration":"Concentra��o, at� 1 minuto","concentration":true,"savingThrow":"Constitui��o"}'::jsonb,'dnd5e')
on conflict (id) do update set name_pt=excluded.name_pt,rank=excluded.rank,is_cantrip=excluded.is_cantrip,is_focus=excluded.is_focus,ruleset=excluded.ruleset,source_book=excluded.source_book,source_page=excluded.source_page,data=excluded.data,system_id=excluded.system_id,updated_at=now();
commit;
